### ISSUE TITLE
material-dark CSS Theme

### ISSUE THREAD

**Issue by Frozen-byte** [syncfusion/ej2-angular-ui-components#10]
Your shipped material-dark CSS theme does not work.
`node_modules/@syncfusion/ej2-layouts/styles/material-dark.css`
Declares white backgrounds for the `.e-card` Class.

My Version is: "@syncfusion/ej2-layouts": "^16.4.47",

**Comment by DeepaLoganathan** [comment]
Hi @Frozen-byte,  

We can reproduce the reported issue at our end in Card component. The fix will be included in our upcoming patch release which is scheduled on 13th February 2019.

You can track the status of this issue with the following link.

https://www.syncfusion.com/feedback/4600/the-background-of-card-is-not-proper-for-material-dark-theme 

Regards, 
Deepa L.

**Comment by karthigeyan92** [comment]
Dear Customer, 
  
The fix for the reported issue is included in our weekly JS2 release V16.4.0.53. 
https://github.com/syncfusion/ej2-javascript-ui-controls/blob/master/controls/layouts/CHANGELOG.md#card

 
Regards, 
Karthigeyan
