### ISSUE TITLE
Schedule cellHeight calculation/margin in rowAutoHeight mode

### ISSUE THREAD

**Issue by jonschoning** [syncfusion/ej2-angular-ui-components#100]
In Release `18.1.46 (2020-04-28)` the following fix was included

> #F12345 - An issue with more indicator height added to timeline height even when rowAutoHeight enabled has been fixed.

This makes the height of the cell in timeline view fit exactly to the height of the appointments when `rowAutoHeight` is enabled.  

![image](https://user-images.githubusercontent.com/137183/81356655-4d537d00-9097-11ea-8c1d-f3737a27edc3.png)

However, the new behavior is undesirable because I need to have space always visible at the bottom of the `cellTemplate` (so that the underlying `cellTemplate` can display information there).  i.e. There is no way to adjust the way the `cellHeight` gets calculated when more appointments are added such that there is always space at the bottom of the `cellTemplate`.

At least previously, the more indicator height provided this space

![image](https://user-images.githubusercontent.com/137183/81356557-11b8b300-9097-11ea-8ffc-b9e4541e783f.png)

but now it is gone in `rowAutoHeight` mode.

I need a way to either get the more indicator height back, or have some way to influence how the new `cellHeight` gets calculated in `rowAutoHeight` mode when appointments are rendered, so that I can ensure there is always visible space at the bottom of the `cellTemplate`.

**Comment by VengateshManiraj** [comment]
Dear Customer,

Greetings from Syncfusion Support.

We have reverted the fix which was included in the #F12345 and the changes will be included in our Volume 1 2020 SP release which is expected to be rolled out on May 13, 2020. We appreciate your patience until then.

Regards,
Vengatesh

**Comment by VengateshManiraj** [comment]
@jonschoning  - We are glad that we have resolved the above-reported problem in our Volume 1 SP release v18.1.52. So we suggest you please upgrade your package version to the latest to overcome this problem.

Sample: https://stackblitz.com/edit/angular-cwokzj-kq2mk2?file=data.ts

**Comment by jonschoning** [comment]
@VengateshManiraj hi Vangatesh, when I try upgrading to v18.1.52 i get an error in my application similar to this https://stackblitz.com/edit/angular-cwokzj-jpcxys?file=app.component.ts
![image](https://user-images.githubusercontent.com/137183/82259035-8eae1d00-9920-11ea-9697-0aaaffc3bd32.png)

I did not see these errors in v18.1.46
