### ISSUE TITLE
Grid: Incorrect filter result when using Excel filter - number filter

### ISSUE THREAD

**Issue by Dschuli** [syncfusion/ej2-angular-ui-components#103]
I get incorrect results when I use the the Excel filter - number filter options (e.g. greater than). Looks like the column content is compared as string, though the column `type` is set to `number`. When I use the normal (not Excel) number filters, I get correct results.

**Comment by manivel-sellamuthu** [comment]
Hi Dschuli, 

Greetings from Syncfusion support. 

We have prepared a sample based on your reported information, but the number filtering is working fine. Please find the below sample for more information. 

Sample: https://stackblitz.com/edit/angular-u3hdn7?file=app.component.html 

If you still faced the issue you, please get back to us with the below details., 

Share the complete Grid code.
Share the dataSource model of the Grid.
If possible, please try to replicate the issue in the given sample.
Share the Syncfusion packages version

The above details are highly required to validate further on this. 

Regards, 
Manivel

**Comment by Dschuli** [comment]
Thanks, Manivel.

Without any (as much as I'm aware of) changes to my code (except maybe a node upgrade) , the reported issue seems to have vanished. Currently, I cannot reproduce it. Excel number filtering works fine now. Pls. regard the issue as closed. Thx a lot.

Regards,

Dschuli
