### ISSUE TITLE
File manager does not work with ShadowDom encapsulation

### ISSUE THREAD

**Issue by mortenmoulder** [syncfusion/ej2-angular-ui-components#105]
I need to run my application in shadow DOM, because I need the styles to be encapsulated within the application, so they don't leak out to the surrounding elements on the page. In general I am basically making a web component. The file manager needs to be implemented on multiple pages.

https://stackblitz.com/edit/angular-vkl91y?file=app.component.ts

Here is a fork of the file manager. The only thing I did was change `ViewEncapsulation.None` to `ViewEncapsulation.ShadowDom`. In the console, I now get a:

>ERROR TypeError: Cannot read property 'addEventListener' of null

Any fix to this?

Steps to reproduce:

1. Go to https://ej2.syncfusion.com/angular/demos/#/material/file-manager/overview
2. Click the "Edit in StackBlitz" button
3. Change `ViewEncapsulation.None` to `ViewEncapsulation.ShadowDom`

**Comment by Shameer-Ali** [comment]
Hi Morten,  
 
We have validated your reported issue with FileManager component. We have logged this as a feature request in FileManager component. This feature will be included in any one of our upcoming release. Generally, we will plan feature based on customer count, feature request and wish list plan. 
  
You can track the status through the below portal link.

https://www.syncfusion.com/feedback/15555/support-for-rendering-the-ej2-components-when-setting-viewencapsulation-as 
  
We appreciate your patience. 
  
Regards,  
Shameer Ali Baig S.

**Comment by PiramanayagamSyncfusion** [comment]
We have closed this issue now. You can track the status through the above portal link. Feel free to reopen the issue and update your comments for the re-investigation.
