### ISSUE TITLE
Change log link broken

### ISSUE THREAD

**Issue by duzenko** [syncfusion/ej2-angular-ui-components#112]
Can't find the change log for @syncfusion/ej2-angular-schedule
The npmjs page (https://www.npmjs.com/package/@syncfusion/ej2-angular-schedule) has a link to https://ej2.syncfusion.com/angular/documentation/release-notes but it's 404

**Comment by VengateshManiraj** [comment]
@duzenko We have resolved the reported problem and refreshed page. Please check the changelog now.
https://www.npmjs.com/package/@syncfusion/ej2-angular-schedule
