### ISSUE TITLE
gantt under 'Manual' taskMode, it still automatically calculated duration and progress.

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#116]
Hi,
We use ej-gantt under 'Manual' taskMode, but it automatically calculated duration and progress and ignored the value I passed. We have a different way to calculate duration and progress. How can I make it use the value I passed?
Thanks

**Comment by gopinathmuniraj** [comment]
Hi yxrgds,
In Gantt, as per the behavior of the tasks with **manual** scheduling mode, the duration and progress will not be calculated automatically. The duration and progress of the manual tasks are rendered as per the data given in the datasource.
**Note**:
1.	The child tasks rendered with the data given in the datasource.
2.	But the **parent task’s** start date, end date, duration and progress value will be calculated based on its own child tasks.
3.	And the child task’s start date, end date and duration value may be changed when [validateManualTasksOnLinking ](https://ej2.syncfusion.com/angular/documentation/api/gantt/#validatemanualtasksonlinking)property set as true. It will validate the tasks, based on the dependency.
4. We have prepared a sample for your reference. In this sample, **the manual child tasks** are rendered with the mapped duration and progress value in the datasource. And the parent task is rendered based on its child task.

Sample: https://stackblitz.com/edit/angular-dehexv-u2dxo5?file=app.component.html
In this given sample, [validateManualTasksOnLinking ](https://ej2.syncfusion.com/angular/documentation/api/gantt/#validatemanualtasksonlinking)is not enabled, so the task’s startDate and duration value will not change based on the dependency value.

If you are still facing same issue the please modify the given sample which we can able to replicate the issue. It will help us to provide exact solution.

**Comment by yxrgds** [comment]
> Hi yxrgds,
> In Gantt, as per the behavior of the tasks with **manual** scheduling mode, the duration and progress will not be calculated automatically. The duration and progress of the manual tasks are rendered as per the data given in the datasource.
> **Note**:
> 
> 1. The child tasks rendered with the data given in the datasource.
> 2. But the **parent task’s** start date, end date, duration and progress value will be calculated based on its own child tasks.
> 3. And the child task’s start date, end date and duration value may be changed when [validateManualTasksOnLinking ](https://ej2.syncfusion.com/angular/documentation/api/gantt/#validatemanualtasksonlinking)property set as true. It will validate the tasks, based on the dependency.
> 4. We have prepared a sample for your reference. In this sample, **the manual child tasks** are rendered with the mapped duration and progress value in the datasource. And the parent task is rendered based on its child task.
> 
> Sample: https://stackblitz.com/edit/angular-dehexv-u2dxo5?file=app.component.html
> In this given sample, [validateManualTasksOnLinking ](https://ej2.syncfusion.com/angular/documentation/api/gantt/#validatemanualtasksonlinking)is not enabled, so the task’s startDate and duration value will not change based on the dependency value.
> 
> If you are still facing same issue the please modify the given sample which we can able to replicate the issue. It will help us to provide exact solution.
Hi gopinathmuniraj，
the child task’sduration and progress are ok. But we also provided duration and progress of parentTask in the datasource as we have a different way to calculate them.  Sometimes, the duration and progress we provided are different with the values calculated by gantt. We modified the duration、 progress back and other values involved  in rowDataBound evnet handler to solve the problem for now. Is there is  better way?
Thanks for your reply.

**Comment by yxrgds** [comment]
> Hi yxrgds,
> In Gantt, as per the behavior of the tasks with **manual** scheduling mode, the duration and progress will not be calculated automatically. The duration and progress of the manual tasks are rendered as per the data given in the datasource.
> **Note**:
> 
> 1. The child tasks rendered with the data given in the datasource.
> 2. But the **parent task’s** start date, end date, duration and progress value will be calculated based on its own child tasks.
> 3. And the child task’s start date, end date and duration value may be changed when [validateManualTasksOnLinking ](https://ej2.syncfusion.com/angular/documentation/api/gantt/#validatemanualtasksonlinking)property set as true. It will validate the tasks, based on the dependency.
> 4. We have prepared a sample for your reference. In this sample, **the manual child tasks** are rendered with the mapped duration and progress value in the datasource. And the parent task is rendered based on its child task.
> 
> Sample: https://stackblitz.com/edit/angular-dehexv-u2dxo5?file=app.component.html
> In this given sample, [validateManualTasksOnLinking ](https://ej2.syncfusion.com/angular/documentation/api/gantt/#validatemanualtasksonlinking)is not enabled, so the task’s startDate and duration value will not change based on the dependency value.
> 
> If you are still facing same issue the please modify the given sample which we can able to replicate the issue. It will help us to provide exact solution.

If you are still facing same issue the please modify the given sample which we can able to replicate the issue. It will help us to provide exact solution.
Hi gopinathmuniraj，
the child task’sduration and progress are ok. But we also provided duration and progress of parentTask in the datasource as we have a different way to calculate them. Sometimes, the duration and progress we provided are different with the values calculated by gantt. We modified the duration、 progress back and other values involved in rowDataBound evnet handler to solve the problem for now. Is there is better way?
Thanks for your reply.

**Comment by karthikeyanraja** [comment]
Hi Yxrgds,

We have analyzed your scenario. We can achieve your requirement by setting taskMode as “Custom”. When the taskMode property is set as Custom, the scheduling mode for each tasks will be mapped from the data source field by taskSettings.manual property.  
Please refer the below code snippet,

[app.component.html]
<ejs-gantt id="TaskMode" [dataSource]="data" taskMode="Custom" >
</ejs-gantt> 

[app.component.ts]
//….
this.data = [
      {
        TaskID: 1,
        //……
        isManual: true,
}];
this.taskSettings = {
      //……
      manual: "isManual"
};

We have also prepared a sample for your reference. Please find the sample from below link,
Sample - https://stackblitz.com/edit/angular-zznrnn?file=app.component.ts 

Please get back to us, If you any further assistance.

Regards,
Karthikeyan Raja

**Comment by yxrgds** [comment]
> Hi Yxrgds,
> 
> We have analyzed your scenario. We can achieve your requirement by setting taskMode as “Custom”. When the taskMode property is set as Custom, the scheduling mode for each tasks will be mapped from the data source field by taskSettings.manual property.
> Please refer the below code snippet,
> 
> [app.component.html]
> <ejs-gantt id="TaskMode" [dataSource]="data" taskMode="Custom" >
> [app.component.ts]
> //….
> this.data = [
> {
> TaskID: 1,
> //……
> isManual: true,
> }];
> this.taskSettings = {
> //……
> manual: "isManual"
> };
> 
> We have also prepared a sample for your reference. Please find the sample from below link,
> Sample - https://stackblitz.com/edit/angular-zznrnn?file=app.component.ts
> 
> Please get back to us, If you any further assistance.
> 
> Regards,
> Karthikeyan Raja

Hi karthikeyanraja ,
Thanks for reply.

I tested the sample you provide. The progress automatic progress calculation is ok with our demands. But actually the duration、endDate and progress is still automatically not maped from the datasource even under 'Custom' taskMode , you can check this sample: https://stackblitz.com/edit/angular-zznrnn-uf72wi?file=app.component.ts .  Therefore, this is ok for us now, while we don't need to calculate duraion include weekends for now.
