### ISSUE TITLE
Angular chart crashes on small data value changes - 100% load on chrome tab - attached example

### ISSUE THREAD

**Issue by joachim-heck** [syncfusion/ej2-angular-ui-components#123]
Hey there, seems like the chart isn't handling very small value changes properly. In the below shown example the chart crashes with 100% load - only killing the chrome tab will help.

Based on the demo area example: https://ej2.syncfusion.com/angular/demos/?_ga=2.119875149.472096534.1599721778-978702163.1550796541#/material/chart/line
**==> RUN IN STACKBLITZ**

Replace the templates code in app.component.html with:
```
<div class="control-section">
    <div align='center'>
        <ejs-chart>
            <e-series-collection>
                <e-series [dataSource]='data' type='Line' xName='x' yName='y' name='Test'></e-series>
            </e-series-collection>
        </ejs-chart>
    </div>
</div>
```

Replace the typescript code in app.component.ts with:
```

import { Component, ViewEncapsulation } from '@angular/core';
import { ILoadedEventArgs, ChartTheme } from '@syncfusion/ej2-angular-charts';
import { Browser } from '@syncfusion/ej2-base';

/**
 * Sample for Line Series
 */
@Component({
    selector: 'app-root',
    templateUrl: 'app.component.html',
    styleUrls: ['app.component.css'],
})
export class AppComponent {
       public data: Object[] = [
        { x: 13.999999999999997, y: 23.999999999999998 }, { x: 14.000000000000001, y: 23.999999999999997 }
    ];
    
    constructor() {
    };
}
```

**Comment by santhoshsubbiah** [comment]
Hi joachim-heck,

We checked your reported issue. That issue is not reproduce in our side. I have attached our sample demo video below.

[demo.zip](https://github.com/syncfusion/ej2-angular-ui-components/files/5522165/demo.zip)

Regards,
Santhosh S

**Comment by sreharii** [comment]
Hi Team, 
  
We are glad to announce that our Essential Studio 2020 Volume 4 service pack release v18.4.0.39 is rolled out and is available for download under the following link. 
  
https://www.syncfusion.com/forums/161973/essential-studio-2020-volume-4-service-pack-release-v18-4-0-39-is-available-for-download 
 
**Sample:** https://stackblitz.com/edit/angular-qzgdt5-8qwxdh?file=app.component.ts
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 
  
Regards,            
Srihari M

**Comment by joachim-heck** [comment]
Nice release - Thank you!
