### ISSUE TITLE
AutoComplete component with  " | async" dataSource does not popup results box

### ISSUE THREAD

**Issue by FredUK** [syncfusion/ej2-angular-ui-components#125]
Hi there,

Not sure if this is a bug with the component but I've been trying to integrate autocomplete component without using DataManager or Query objects but when doing so it instantly shows and hides the results box.

I'm hooking into the (filtering) event and using a service to perform a backend call which returns an observable. 
The observable is being passed to the DataSource property as `data | async`. 

It seems that the component doesn't show the popup after the observable has changed. 
I've tried using `pipe(tap() )` to manually call showPopup() on the component and this causes the results box to instantly show and hide which is not ideal.

```
 <ejs-autocomplete 
            #autocompleteObj 
            [dataSource]='filteredData | async'
            (filtering)="onFilter($event)"
            .....
            '></ejs-autocomplete>
```

```
    public onFilter(args: any): void {
      args.preventDefaultAction = true;
      this.filteredData = this.dataService.fetch(args.text)
    }
```

[Stackblitz demo here](https://stackblitz.com/edit/angular-wwjr8b?file=app.component.ts)

Can you confirm if this is a bug?

**Comment by PonmaniMurugaiyan** [comment]
Hi @FredUK ,

Thanks for contacting Syncfusion support.

We have validated your reported query and modified the provided sample. We would like to inform you that, directly assigning the async value to datasource variable will not be reflected. So we suggest you to update through updateData method in filtering event of AutoComplete. Please find the code snippet and test sample below for reference.

```java
// Event handler for filter event on component
public onFilter(args: any): void {
    args.preventDefaultAction = true;
    let data =  this.dataService.fetch(args.text).subscribe(result => { 
      this.dataArray= result; 
    }) 
   args.updateData(this.dataArray,null);
}
```

**Sample**: https://stackblitz.com/edit/angular-wwjr8b-vs3mnq?file=app.component.ts  

Kindly check with the above sample. Please get back us if you need further assistance.

Regards,
Ponmani M
