### ISSUE TITLE
Schedule: Multiple issues with activeView.getRenderDates()

### ISSUE THREAD

**Issue by FredUK** [syncfusion/ej2-angular-ui-components#126]
Hi,

I found a couple of issues related to getRenderDates(). It seems that sometimes the data returned is invalid or not refreshed properly:

- When switching to month view, calling `activeView.getRenderDates()` returns invalid date ranges (only 1 date). When navigating to the next or previous month then dates are correct.

- When switching from month to work week, it returns date ranges for the month view, not week (didn't refresh args?). Switching from any other view to "work week" works fine, just not from month to work week.

- Some inconsistencies when moving from and to Agenda view: from month to agenda it shows the whole month (didn't refresh args?), then navigating next period in Agenda only shows 1 date object in args.

I've tried using `activeView.getStartDate()` and `getEndDate()` instead but it suffers from the same issues as it depends on getRenderDates internally.

This means that when using the Schedule component without DataManager it is impossible to get a service to fetch the correct data to display on the calendar because there is no accurate way of getting the startDate and EndDate of the currentView.

Ideally whenever a UI action causes the calendar to switch to a different view or a different date range, a new event `dateRangeChange` should be triggered so that the user can handle it accordingly. For now a user either needs to hook to multiple events `selectedDateChange`, `currentViewChange` and try and calculate the proper start and end times which is not ideal..

Another event should also be triggered when the calendar instantiates and it should include helpful args such as current view, initial date range etc. For now I'm using ngAfterViewContentInit in combination with a setTimeout so that I have access to the activeView, but using setTimeout to wait for activeView to get instantiated is not ideal. It would be better if a final event was triggered from the ScheduleComponent with the args mentioned before.

[Stackblitz demo here](https://stackblitz.com/edit/angular-uhqgrm?file=app.component.ts)

**Comment by sellakumark** [comment]
@FredUK - We had validated your reported problem at our end. The solution for your queries as follows,

When we perform navigation between previous or next dates or changing view from month to work week or agenda views, the proper dates can be generated once the action has been completed. We can get the proper current view dates in actionComplete event using the getCurrentViewDates public method.

In our scheduler, there is no event like selectedDateChange and currentViewChange to perform the actions. To know more about the scheduler API, kindly refer to the API documentation in the below link

https://ej2.syncfusion.com/angular/documentation/api/schedule/

For your reference, we had prepared the simple sample based on your requirement which is available in below link

https://stackblitz.com/edit/angular-uhqgrm-wttrxv?file=app.component.ts

Kindly try the above sample and documentation link and get back to us for further assistance.
