### ISSUE TITLE
Using an output event causes build failure (TS2722: Cannot invoke an object which is possibly 'undefined')

### ISSUE THREAD

**Issue by buu700** [syncfusion/ej2-angular-ui-components#129]
I assume this is a general issue, but I'm specifically using `<ejs-schedule (actionComplete)` with strict mode.

[According to the Angular team](https://github.com/angular/angular/issues/38342#issuecomment-668753033), Syncfusion needs to switch over to `EventEmitter` or make its custom `EmitType` 100% compatible.

**Comment by kumaresan-subramani** [comment]
Hi @buu700 ,

 
Thank you for contacting Syncfusion support.
 

We appreciate your effort for the pull request and we have already logged this as a bug that you can refer from the below feedback.

**Feedback**: https://www.syncfusion.com/feedback/17157/need-provide-support-for-strict-mode-compilation-in-angular-grid



We expect that it will be included with our upcoming patch release scheduled on **October 13, 2020**.
 

Please get back to us if you need any further assistance.

**Comment by buu700** [comment]
Glad to hear that, and thanks for the quick follow-up! I'm not able to view that issue, but if this is planned for release in less than a week then that's good enough for me. Just let me know if I need to sign a CLA or anything like that.

**Comment by dragouf** [comment]
I still have this error when I try to use (actionBegin) on grid with angular 11.1 in strict mode. Is it really fixed ?

**Comment by BrandonQDixon** [comment]
I am also experiencing this issue with angular 11 in strict mode.

**Comment by jesusarockias** [comment]
Hi @dragouf & @BrandonQDixon ,

Sorry for the inconvenience. We need to change the in even invoking architecture which involves extensive testing before rolling out. So, we are not able to deliver this on time and we are working on this. We expect that it will be available with our Volume 1, 2021 SP release. We request you to support on this until then.

**Comment by jesusarockias** [comment]
Hi All,

We are glad that we have completed this issue and it is published with our patch release version “19.1.58”. 

https://ej2.syncfusion.com/angular/documentation/release-notes/19.1.58/?type=all#common

Please get back to us if you have any queries.

**Comment by tyeety** [comment]
Updated to 19.1.59, problem still exists!

error TS2722: Cannot invoke an object which is possibly 'undefined'.
(recordDoubleClick)="grid_recordDoubleClick($event)"

**Comment by Mydeen-SN** [comment]
Hi @tyeety ,

We have resolved the event related issues in Syncfusion Angular packages, you can use the latest angular packages which will resolve the issue.
