### ISSUE TITLE
documenteditor top ribbon right and left arrows are not working in RTL

### ISSUE THREAD

**Issue by elbaza** [syncfusion/ej2-angular-ui-components#13]

**Comment by karthigeyan92** [comment]
Hi Elbaza, 

Greetings from Syncfusion.

We logged the below bug report and fix will include in JS2 weekly release on April 23, 2019. 
https://www.syncfusion.com/feedback/5757/toolbar-scroller-is-not-working-in-mozilla-when-we-enable-rtl-mode 
 
Regards, 
Karthi

**Comment by karthigeyan92** [comment]
Hi Elbaza,

Kindly upgrade to 17.1.43 version, to avail the fix.
https://stackblitz.com/edit/6or9wz?file=index.ts

Regards,
Karthi

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution already provided.
