### ISSUE TITLE
bug of gantt costom column template 

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#132]
![image](https://user-images.githubusercontent.com/30115801/98359552-67304580-2063-11eb-97ed-d91ccff3349e.png)
There is the example: https://stackblitz.com/edit/angular-fab3cp?file=app.component.ts

**Comment by poojapriya-krishnamoorthy** [comment]
Hi YangXiao,
Thanks for sharing the issue reproducible sample.
We are able to replicate the issue when template column is used as a tree column index. We already logged bug report for this. The status can be tracked from below feedback link.
https://www.syncfusion.com/feedback/19111/template-column-is-not-working-properly-while-editing-if-we-use-it-as-tree-column
The fix will be provided on the patch release which is expected to be rolled out on November 11, 2020.  

Until the you can change the index as like below code example.

`**[component.html]**
<ejs-gantt [treeColumnIndex] = "0 "
</ejs-gantt>
`

**Comment by poojapriya-krishnamoorthy** [comment]
Hi YangXiao
The reported issue can be resolved in sample level. The id of task name column and progress column are same. We have modified the sample, by mapping different id’s in column template as like below code example.
```
<ejs-gantt >
    <e-columns>
        <e-column field='TaskID' headerText='序号'></e-column>
        <e-column field='TaskName' headerText='任务名称'>
            <ng-template #template let-data>
               //...
            </ng-template>
        </e-column>
        <e-column field='customProgress' headerText='Progress'>
            <ng-template #template1 let-data>
                //...
            </ng-template>
        </e-column>
    </e-columns>
</ejs-gantt>
```
[Sample](https://stackblitz.com/edit/angular-fab3cp-32nrof?file=app.component.html)

**Comment by yxrgds** [comment]
> Hi YangXiao
> The reported issue can be resolved in sample level. The id of task name column and progress column are same. We have modified the sample, by mapping different id’s in column template as like below code example.
> 
> ```
> <ejs-gantt >
>     <e-columns>
>         <e-column field='TaskID' headerText='序号'></e-column>
>         <e-column field='TaskName' headerText='任务名称'>
>             <ng-template #template let-data>
>                //...
>             </ng-template>
>         </e-column>
>         <e-column field='customProgress' headerText='Progress'>
>             <ng-template #template1 let-data>
>                 //...
>             </ng-template>
>         </e-column>
>     </e-columns>
> </ejs-gantt>
> ```
> 
> [Sample](https://stackblitz.com/edit/angular-fab3cp-32nrof?file=app.component.html)

Hi,poojapriya-krishnamoorthy ,

Thanks for reply.

Using  different id’s in column template actually didn't work. The custom column template seems can only use template id 'template', and it ignores the custom column template when using othen template id. You can check the [sample](https://stackblitz.com/edit/angular-fab3cp-xhjhsm?file=app.component.html).

**Comment by yxrgds** [comment]
Hi poojapriya-krishnamoorthy,
We are now eager to using the virtul scroll feature of the latest version, but this bug is preventing me from the latest version of gantt chart. We are now using v18.2.56, under which version the custom column template feature is ok. ,
Hope this bug can be fixed soon.
Thanks.

**Comment by yxrgds** [comment]
> Hi poojapriya-krishnamoorthy,
> We are now eager to using the virtul scroll feature of the latest version, but this bug is preventing me from the latest version of gantt chart. We are now using v18.2.56, under which version the custom column template feature is ok. ,
> Hope this bug can be fixed soon.
> Thanks.

Hi，
@poojapriya-krishnamoorthy @ajithr 
Sorry to bother you again. It is a bug confirmed or I had the wrong way to use custom column template. It is preventing me from the latest version of gantt. 
Looking forward to your reply.
Thanks.

**Comment by MonishaSivanthilingam** [comment]
Hi YangXiao,

We have analyzed your query and would like to inform you that this is not a bug in Gantt. In the latest version of the Gantt, the column template works even if we give the same id for different columns. We have modified a sample with the latest versions to fix the issue. Please find the sample from the below link.

**Sample:** https://stackblitz.com/edit/angular-fab3cp-ukmhze?file=app.component.html

Please contact us if you require any further assistance.

Regards,
Monisha.

**Comment by yxrgds** [comment]
> Hi YangXiao,
> 
> We have analyzed your query and would like to inform you that this is not a bug in Gantt. In the latest version of the Gantt, the column template works even if we give the same id for different columns. We have modified a sample with the latest versions to fix the issue. Please find the sample from the below link.
> 
> **Sample:** https://stackblitz.com/edit/angular-fab3cp-ukmhze?file=app.component.html
> 
> Please contact us if you require any further assistance.
> 
> Regards,
> Monisha.

Hi MonishaSivanthilingam,
I checked the latest version of gantt, this is ok. 
Thanks.
