### ISSUE TITLE
ej2-angular-spreadsheet Formula cell (re-)selection not working properly

### ISSUE THREAD

**Issue by Hikariii** [syncfusion/ej2-angular-ui-components#133]
## New formula: cell selection works:
When I insert a formula in a cell I get a nice cell-selection mode where I can click-drag the cells/range for my formula.
This works fine like this:

![spreadsheet-new-formula-cells](https://user-images.githubusercontent.com/1484903/99526456-8f8d3d80-299b-11eb-91fc-72e5bc9d403e.gif)

## Edit formula: cell selection does not work:
But when I re-select the cells I expect it to work like the same, but is does not. There is no cell selection for my formula.

![spreadsheet-adjust-formula-cells](https://user-images.githubusercontent.com/1484903/99526704-f14da780-299b-11eb-835b-30a11767ddec.gif)

## How it should work (ms-excel)
But when I re-select the cells I expect it to work like Excel:

![excel-adjust-formula-cells](https://user-images.githubusercontent.com/1484903/99526578-b9defb00-299b-11eb-8373-bac616305b30.gif)

**Comment by sangeethapriyaM** [comment]
Hi Team,

We have checked your reported requirement and we considered this as an improvement. And the fix will be available our Essential studio volume 1 2021 release. We appreciate your patience until then. 

Regards,
Sangeetha M

**Comment by syncsiva** [comment]
This issue has been resolved in the latest version. Please feel free to reopen if you have any further queries.
https://ej2.syncfusion.com/demos/#/bootstrap5/spreadsheet/formula.html
