### ISSUE TITLE
Annotation HTML Events on PdfViewer take too long 

### ISSUE THREAD

**Issue by begandroide** [syncfusion/ej2-angular-ui-components#134]
Hello! Im working with Angular 10, and .Net core, using developer licence of Syncfusion, and im facing issues about performance with the module of PdfViewer when annotations textfree is maked.

Problem: When annotation is being created (typing in an existent or in a new), the event `keydown` take too long and has warnings of [violation] en chrome devTools with verbose mode (attach screenshot).
![image](https://user-images.githubusercontent.com/22018004/99853576-0116e880-2b62-11eb-95ea-dc03417dff30.png)

The above warnings appear when user is typing an annotation in pdfViewer.

Im facing the same issue in the demo page of angular [https://ej2.syncfusion.com/angular/demos/#/material/pdfviewer/default](https://ej2.syncfusion.com/angular/demos/#/material/pdfviewer/default), not with the same event but has warnings and sometimes take a while to finish typing.

Regards

**Comment by DhivyaBharathi1307** [comment]
"urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/DHIVYA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/DHIVYA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/DHIVYA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;color:black;
mso-color-alt:windowtext;background:white'>Hi Team,</span><span
style='font-size:11.0pt;line-height:150%;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:
minor-latin;background:white'><o:p></o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;background:
white'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;color:black;
mso-color-alt:windowtext;background:white'>We have improved the performance
while adding the text in the free text annotations in our latest version
v19.4.0.50. Kindly upgrade to that version and let us know whether the reported
issue is resolved or not. We have shared the sample in the latest version
v19.4.0.50.</span><span style='font-size:11.0pt;line-height:150%;font-family:
"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:
minor-latin;mso-bidi-theme-font:minor-latin;background:white'><o:p></o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;background:
white'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;color:black;
mso-color-alt:windowtext;background:white'>Sample: <a
href="https://stackblitz.com/edit/angular-esymus?file=app.component.ts">https://stackblitz.com/edit/angular-esymus?file=app.component.ts</a>
</span><span style='font-size:11.0pt;line-height:150%;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:
minor-latin;background:white'><o:p></o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;background:
white'><o:p>&nbsp;</o:p></span></p>

<p style='margin-top:0in;margin-right:0in;margin-bottom:7.5pt;margin-left:0in;
text-align:justify;line-height:18.0pt;background:white'><span style='font-size:
11.0pt;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;color:#111111'>Packages:&nbsp;&nbsp;&nbsp;&nbsp;</span><span
style='font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin'><o:p></o:p></span></p>



Service side   package | ASP.NET Core :           https://www.nuget.org/packages/Syncfusion.EJ2.PdfViewer.AspNet.Core.Windows/https://www.nuget.org/packages/Syncfusion.EJ2.PdfViewer.AspNet.Core.Linux/            https://www.nuget.org/packages/Syncfusion.EJ2.PdfViewer.AspNet.Core.OSX/   ASP.NET MVC:           https://www.nuget.org/packages/Syncfusion.EJ2.PdfViewer.AspNet.Mvc5/   https://www.nuget.org/packages/Syncfusion.EJ2.PdfViewer.AspNet.Mvc4/
-- | --




<p style='margin:0in;line-height:18.0pt;background:white'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-ascii-theme-font:
minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;
color:black;mso-color-alt:windowtext'><br style='mso-special-character:line-break'>
<![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
<![endif]></span><span style='font-family:"Calibri",sans-serif;mso-ascii-theme-font:
minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin'><o:p></o:p></span></p>

<p class=MsoNormal style='line-height:115%'><span style='font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:
minor-latin'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='line-height:115%'><span style='font-family:"Calibri",sans-serif'>CDN:
</span><a href="https://cdn.syncfusion.com/ej2/19.4.50/material.css"><span
style='font-family:"Calibri",sans-serif'>https://cdn.syncfusion.com/ej2/19.4.50/material.css</span></a><span
style='font-family:"Calibri",sans-serif'> <o:p></o:p></span></p>

<p class=MsoNormal style='line-height:115%'><span style='font-family:"Calibri",sans-serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='line-height:150%'><a
href="https://cdn.syncfusion.com/ej2/19.4.50/dist/ej2.min.js"><span
style='font-family:"Calibri",sans-serif'>https://cdn.syncfusion.com/ej2/19.4.50/dist/ej2.min.js</span></a><span
style='font-size:11.0pt;line-height:150%;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:
minor-latin;background:white'><o:p></o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;background:
white'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;color:black;
mso-color-alt:windowtext;background:white'>Regards,</span><span
style='font-size:11.0pt;line-height:150%;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:
minor-latin;background:white'><o:p></o:p></span></p>

<p class=MsoNormal style='line-height:150%'><span style='font-size:11.0pt;
line-height:150%;font-family:"Calibri",sans-serif;mso-ascii-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:minor-latin;color:black;
mso-color-alt:windowtext;background:white'>Dhivya.</span><span
style='font-size:11.0pt;line-height:150%;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-theme-font:
minor-latin;background:white'><o:p></o:p></span></p>


</body>

</html>

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
