### ISSUE TITLE
gantt eventMarker 

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#136]
Currently，gantt eventmarker are all at the same height, leading to the previous eventmarker covered by the 
the latter, We expect they can be at different height.

Currently: ([sample](https://stackblitz.com/edit/angular-6iqyec?file=app.component.ts))
![image](https://user-images.githubusercontent.com/30115801/100317992-40c55080-2ff8-11eb-9ffb-5a140806bace.png)
What we expect:
![image](https://user-images.githubusercontent.com/30115801/100318121-7b2eed80-2ff8-11eb-9783-d3f6a6687ad9.png)

Currently, we change the dom the realize this. But we don't think this is a good way. Is there a better way or  will be a plan of 
 new function of this?

Thanks
yxrgds.

**Comment by gopinathmuniraj** [comment]
Hi Yxrgds, 
Thanks for contacting Syncfusion support. 
We have analyzed your query. Currently we have not having the support for changing the position of event markers in the chart side.  
We like to inform you that, we can start the feature once you confirm the below details. 

1. We couldn’t set the positions of event markers in pixels based on our requirements.
2. We can change the position of event markers only like top, middle or bottom of the Gantt chart.

Please let us know, is this kind of support is good for you? Your confirmation will be helpful for us to log the feature report asap. 
Thanks, 
Gopinath M

**Comment by yxrgds** [comment]
> Hi Yxrgds,
> Thanks for contacting Syncfusion support.
> We have analyzed your query. Currently we have not having the support for changing the position of event markers in the chart side.
> We like to inform you that, we can start the feature once you confirm the below details.
> 
> 1. We couldn’t set the positions of event markers in pixels based on our requirements.
> 2. We can change the position of event markers only like top, middle or bottom of the Gantt chart.
> 
> Please let us know, is this kind of support is good for you? Your confirmation will be helpful for us to log the feature report asap.
> Thanks,
> Gopinath M

Hi gopinathmuniraj,
Thanks for your reply.
We don't need specific height of  event markers. We expect the event marker are close to  the former will not cover the label of the former. For instance, these is a event marker on 2020/12/09 with label 'test lable 1'，and there comes event marker on 2020/12/10 with label 'test label 2'. We expect the label 'test label 2' won't cover the label  'test lable 1'. Currently, we change the dom make the event marker has 6 different height for  recycle use. 
![image](https://user-images.githubusercontent.com/30115801/101562774-03eb5780-3a03-11eb-830a-0e03815fb97a.png)

**Comment by MonishaSivanthilingam** [comment]
Hi Yxrgds,

Currently, we do not have support to render event markers at different height. However, we have logged a feature report for this. You can track its status from the below feedback link.

**Feedback:** https://www.syncfusion.com/feedback/22778/provide-support-to-render-event-markers-in-different-heights

However, as we have already lined up some major features, we could not implement this support immediately. We will implement this and include it in any of our upcoming releases. Please cast your vote on this feature based on the customer demand we will prioritize the features in our upcoming road map.

Regards,
Monisha.
