### ISSUE TITLE
How to keep the eventmarker always visible while scrolling the gantt chart up and down?

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#138]
Hi,
I want to know is there a way to keep the eventmarker always visible while scrolling the gantt chart up and down. Currently I can only acheive this by listening to scroll event and change dom. I think gantt will be better with this feature.
![image](https://user-images.githubusercontent.com/30115801/100319584-d661df80-2ffa-11eb-9ca6-ba7440d70d34.png)

**Comment by gopinathmuniraj** [comment]
Hi Yxrgds, 
Thanks for contacting Syncfusion support. 
We have analyzed your query. Currently we are not having the support to maintain the event markers always visible while scrolling the Gantt chart up and down. We have logged feature report for this. The status can be tracked through the below feedback link. 
Feedback link:  https://www.syncfusion.com/feedback/20213/to-maintain-the-event-markers-always-visible 
As we have already lined up some major features, we could not this support immediately. We will implement this and include it in any of our upcoming releases. Please cast your vote on this feature based on the customer demand we will prioritize the features in our upcoming road map.   
Thanks, 
Gopinath M

**Comment by yxrgds** [comment]
> Hi Yxrgds,
> Thanks for contacting Syncfusion support.
> We have analyzed your query. Currently we are not having the support to maintain the event markers always visible while scrolling the Gantt chart up and down. We have logged feature report for this. The status can be tracked through the below feedback link.
> Feedback link: https://www.syncfusion.com/feedback/20213/to-maintain-the-event-markers-always-visible
> As we have already lined up some major features, we could not this support immediately. We will implement this and include it in any of our upcoming releases. Please cast your vote on this feature based on the customer demand we will prioritize the features in our upcoming road map.
> Thanks,
> Gopinath M

Hi gopinathmuniraj,
Thanks for reply.

I have a problem to open the feedback link.
![image](https://user-images.githubusercontent.com/30115801/101562935-50369780-3a03-11eb-8d69-3d8bec71979d.png)

**Comment by MonishaSivanthilingam** [comment]
Hi Yxrgds,

We have fixed the issue with the feedback [20213](https://www.syncfusion.com/feedback/20213/to-maintain-the-event-markers-always-visible). You will be able to view the feedback now without any issues.

We apologize for the inconvenience caused.

Regards,
Monisha.

**Comment by yxrgds** [comment]
The latest version of gantt has supported this request
