### ISSUE TITLE
Date range selected without click on "Apply" button

### ISSUE THREAD

**Issue by anoopyadav-kiwi** [syncfusion/ej2-angular-ui-components#14]
Hello Team,

My date was selected if I select the date range and clicked outside the date range picker. Is there any method so that my date will be select only when I press apply button.

Please response ASAP. I got stuck into this.

Thanks in Advance.

**Comment by BerlyChristopher94** [comment]
Hi Anoopyadav,

We have checked with your requirement and prepared the sample to apply the selected date range for DateRangePicker while clicking on **Apply** button only by using “**Change**” event as like in the below code example. 

**[app.component.html]**

```
<div class="control-section">
       <div id="control_wrapper"> 
          <ejs-daterangepicker #daterange (change)="onChange($event)" (open)="onOpen($event)"></ejs-daterangepicker>       
        </div>
</div>
```

`
**[app.component.ts]**

`export class DefaultDateRangePickerComponent {
  public preValue;
  @ViewChild('daterange')
  public DateRangeObj: DateRangePickerComponent;
  onChange(args) {
    // if clicking the document prevents to update the selected value
    if(args.event && !(args.event.target.classList.contains('e-apply'))) {
      this.DateRangeObj.value = this.preValue;
    }
    else
    return false;
  }
  onOpen(args) {
    // Store the previous value
    this.preValue = args.model.value;
  }
}

`

Please find the sample from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-f3xkgj-panfck?file=default.component.ts 

Regards,
Berly B.C

**Comment by anoopyadav-kiwi** [comment]
Thanks for your quick reply.

I had tried your solution and it's working fine.
