### ISSUE TITLE
gantt chart can not scroll smoothly when there are too many tasks.

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#140]
There is a [simple](https://stackblitz.com/edit/angular-6iqyec?file=data.ts).

When there are too many tasks, gantt chart can not scroll up and down smoothly, especially with 
Poorly configured computer. Actually the whole page is not smooth. When you scroll up and down, you will find the the left gantt tree grid did synchronously scroll with right gantt chart grid. In this [page](https://angular-6iqyec.stackblitz.io), it will be better. 

Actually, we have the problem when using gantt chart.

Maybe gantt chart can use scroll virtualization to optimize this. There is a [component ](https://demo.grapecity.com.cn/wijmo/demos/Grid/PagingScrolling/ScrollVirtualization/angular)which used this techni to reduce the dom number of the page. But I am sorry the page is in Chinese.

Additionaly, I find there is console error, when resize the stackblitz page.
![image](https://user-images.githubusercontent.com/30115801/100324105-b255cc80-3001-11eb-9d09-519a98ddc809.png)
![image](https://user-images.githubusercontent.com/30115801/100324145-c3064280-3001-11eb-897d-4f9b65a6762b.png)

**Comment by gopinathmuniraj** [comment]
Hi Yxrgds, 
Thanks for contacting Syncfusion support. 
 
When we have too many tasks in Gantt, the performance can be improved by using the Virtualization support. 
 
Currently, we don’t have virtualization support in Gantt, we have already logged a feature report for this. You can track the status from the [feedback link](https://www.syncfusion.com/feedback/7733/virtual-scrolling-support-for-gantt). 
 
Now, we are working on Gantt chart implementation in Blazor platform with high priority. So, we unable to deliver the feature as promised.  However, we have the plan to implement the virtual scrolling feature in the Gantt chart in Volume 4, 2020 which is expected to be rolled out on end of December.  
 
We appreciate your patience until then. 
Thanks, 
Gopinath M
