### ISSUE TITLE
@syncfusion/ej2-angular-richtexteditor@18.4.34 version not installing

### ISSUE THREAD

**Issue by surbhiAscendo** [syncfusion/ej2-angular-ui-components#148]
So just after the 18.4.34 version was released I couldn't install the package, it gives me the following error:

npm install @syncfusion/ej2-angular-richtexteditor --save
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @syncfusion/ej2-richtexteditor@18.4.34.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@syncfusion/ej2-angular-richtexteditor'

npm ERR! notarget 

Can you please help with this?

**Comment by Indrajith-Sync** [comment]
Hi @surbhiAscendo ,
 
Sorry for the inconvenience caused, 
 
We have resolved the reported issue “**npm ERR! notarget No matching version found for @syncfusion/ej2-richtexteditor@18.4.34**” from our end. Can you try re-installing the package, and check the reported issue form your end ?
