### ISSUE TITLE
How to do pdf export in syncfusion grid?

### ISSUE THREAD

**Issue by rajkumar302598** [syncfusion/ej2-angular-ui-components#150]
HI Syncfusion,

I want use Syncfusion grid, I have referred your docs which helps me to design your grid like below sample

https://stackblitz.com/edit/angular-vmrrj6-gxnuhb?file=app.component.ts

I want to generate this grid into pdf file with same styles?

is this possible? if yes let know any reference

**Comment by sujithvj** [comment]
Hi Rajkumar,

Greetings from Syncfusion and sorry for the delay in provide the response.

You can achieve your requirement of applying the Grid’s customized style properties in the PDF export using the Grid’s pdfQueryHeaderCellInfo and pdfQuerycellInfo events. The pdfQueryHeaderCellInfo event will trigger for each header cell rendering in the PDF document using which you can apply custom CSS in to the grid’s header cell and the pdfQueryCellInfo will trigger for each content cell rendering in the PDF document using which you can customize the cell styles based on condition.

Please refer the below code example and sample for more information,

`// Grid’s beforePdfExport event handler
beforePdfExport() {
    // A global empty string property is defined for row span case
    this.dataVal = "";
}

// Grid’s toolbarClick event handler
toolbarClick(args) {
    const pdfExportProperties: PdfExportProperties = {
        pageOrientation: "Landscape"
    };
    this.grid.pdfExport(pdfExportProperties);
}

// Grid’s pdfQueryCellInfo event handler
pdfQueryCellInfo(args) { 
    // Here the corresponding styles for the cell content is applied 
    if (args.column.field === "Date") { 
        if (this.dataVal != args.value) { 
            args.cell.rowSpan = 3; 
        } 
            this.dataVal = args.value; 
    } 
    if (args.column.field == "Total") { 
        args.style = { backgroundColor: "#e0e0d1" }; 
    } 
    if (args.data["Date"] === "Total" && args.cell.row.rowIndex > this.dummyData.length - 4) {   
        args.style = { backgroundColor: "#ffbb33" }; 
        let color: PdfColor = new PdfColor(0, 0, 0); 
        let width: number = 1; 
        let pen: PdfPen = new PdfPen(color, width); 
        let border: PdfBorders = new PdfBorders(); 
        border.all = pen; 
        args.cell.style.borders = border; 
        args.cell.style.font = new PdfStandardFont(PdfFontFamily.TimesRoman, 10, PdfFontStyle.Bold); 
    } 
} 

// Grid’s pdfHeaderQueryCellInfo event handler
pdfHeaderQueryCellInfo(args) { 
    // Here the corresponding styles for the header cell content is applied
    args.cell.style.backgroundBrush = new PdfSolidBrush(new PdfColor(204, 51, 153)); 
}
`

**Sample:** https://stackblitz.com/edit/angular-vmrrj6-uh6aii?file=app.component.ts

More details on this can be checked in the below documentation links,

**Documentation:** https://ej2.syncfusion.com/angular/documentation/grid/pdf-export/#conditional-cell-formatting

**API links:** https://ej2.syncfusion.com/angular/documentation/api/grid/#pdfquerycellinfo
                  https://ej2.syncfusion.com/angular/documentation/api/grid/#pdfheaderquerycellinfo

Let us know if you have any concerns.

Regards,
Sujith R
