### ISSUE TITLE
How to get event while changing intervals on Period Selector?

### ISSUE THREAD

**Issue by ibhargav90** [syncfusion/ej2-angular-ui-components#151]
I have this period selector in my component,
Now when I switch from one interval to another, I can't get any events where I can put my custom logic (Let's say aggregation) .
What is event where I can get intervalType change ?

  periods: PeriodsModel[] = [
        { intervalType: 'Minutes', interval: 1, text: '1m', selected: true },
        { intervalType: 'Minutes', interval: 30, text: '30m' },
        { intervalType: 'Hours', interval: 1, text: '1H' },
        { intervalType: 'Hours', interval: 12, text: '12H' },
        { intervalType: 'Auto', text: '1D' },
    ];

**Comment by sreharii** [comment]
Hi Bhargav,

We have validated your query. We have considered the reported scenario as a feature and logged a feature request for this. This feature will be available in any of our releases. We appreciate your patience until then. You can keep track of the feature request from the feedback portal below. 
 
Feedback Link: https://www.syncfusion.com/feedback/22463/need-to-provide-event-support-for-period-selector-change           
  
The provided feedback link is private, and you need to login to view this feedback. 
  
If you have any more specifications/precise replication procedures or a scenario to be tested, you can add it as a comment in the portal. 

Regards,
Srihari M
