### ISSUE TITLE
problem with rowSelect args

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#156]
The rowSelect event args gives the rowIndexes of selected rows which makes it difficult to get the data of selected rows while mutiselect with 'ctrl' key after using column filter. As you can see in the picture, I filter the column first, then multiselect 3 rows with 'ctrl’ key. And I want get the data of 3 selected rows, but only got the rowIndexes [0,1,2].
![image](https://user-images.githubusercontent.com/30115801/109943369-175f4380-7d10-11eb-9272-7caaf66da6d8.png)
Here is the [sample](https://stackblitz.com/edit/angular-2defdf-7pepfg?file=app.component.html).

**Comment by yxrgds** [comment]
> The rowSelect event args gives the rowIndexes of selected rows which makes it difficult to get the data of selected rows while mutiselect with 'ctrl' key after using column filter. As you can see in the picture, I filter the column first, then multiselect 3 rows with 'ctrl’ key. And I want get the data of 3 selected rows, but only got the rowIndexes [0,1,2].
> ![image](https://user-images.githubusercontent.com/30115801/109943369-175f4380-7d10-11eb-9272-7caaf66da6d8.png)
> Here is the [sample](https://stackblitz.com/edit/angular-2defdf-7pepfg?file=app.component.html).

There is still a way to get the data of selected rows. I just think the args is not proper.

**Comment by MonishaSivanthilingam** [comment]
Hi Yxrgds,

Thank you for contacting Syncfusion support.

You can get the data of the selected records from the getSelectedRecords() method. By using this method you can get the data of the selected records and it also works for multiple records too. 

We have also prepared a sample for your reference. Please find the sample from the below link.

**Sample:** https://stackblitz.com/edit/angular-bqzses-lrwytd?file=app.component.ts

Please contact us if you require any further assistance.

Regards,
Monisha.

**Comment by yxrgds** [comment]
Thanks
