### ISSUE TITLE
Copy past of bullet  point lines from MS office to Angular WYSIWYG missing second lines

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#159]
We found a weird error in Angular Rich text editor but not in React , Vue and Java script Rich text Editor.

Sample word document is attached here for reference. the content copy past was not working with Angular RTE editor demo of Syncfusion too.

if you copy past the attached content to Angular Rich text editor you can fine easily that second line will not be pasted.
[angular RTE editore issues.docx](https://github.com/syncfusion/ej2-angular-ui-components/files/6184108/angular.RTE.editore.issues.docx)
Kindly advise to resolve and why this issues only on Angular RTE???

**Comment by revanthSyncfusion** [comment]
Hi Arun, 
 
 
Greetings from Syncfusion support. 
 
 
We have validated your query and have considered **“Pasting list with 'outline level' style in the MS Word not working properly in the Rich Text Editor”** as a bug from our end and logged the report for the same and the fix will be included in our patch release on 7th April.   
      
You can now track the current status of the report, review the proposed resolution timeline, and contact us for any further inquiries through this link: [https://www.syncfusion.com/feedback/23584](https://www.syncfusion.com/feedback/23584)
 
Regards, 
Revanth

**Comment by arunjoshtech** [comment]
Dear Revanth,
Really thanks for your reply and commitment towards to this bug. Since this bug is not found in any Rich text editor which we tested all together. So kindly make it to improve the project.

**Comment by arunjoshtech** [comment]
Dear Revanth,
Any update on bug fixes release?
please advise

**Comment by Indrajith-Sync** [comment]
Hi @arunjoshtech ,

Thanks for your patience,

We have resolved the reported issue “Pasting list with 'outline level' style in the MS Word not working properly in the Rich Text Editor” with the package version **19.1.56**.

Release Notes: https://ej2.syncfusion.com/angular/documentation/release-notes/19.1.56/?type=all#richtexteditor

Can you please upgrade your package to this version to resolve the reported issue? 

Regards,
Indrajith

**Comment by arunjoshtech** [comment]
Thanks
