### ISSUE TITLE
[GRID] Empty message with frozen column

### ISSUE THREAD

**Issue by gianlucainnocente** [syncfusion/ej2-angular-ui-components#166]
Hello, i'm using the Syncfusion Grid with a frozen column at the end.
It is working well but, when the grid is empty, the empty message is showed into the frozen column and this is not very good (see attachment).

How can i move the empty message to the left?

Thanks

![Schermata 2021-04-16 alle 11 54 59](https://user-images.githubusercontent.com/11719036/115007712-936daf00-9eaa-11eb-9036-818e865f20ea.png)

**Comment by rajapandiravi1009** [comment]
Hi Customer,

Greetings from syncfusion support

Based on our Grid architecture, we rendered separate tables for both frozen and movable parts in the Grid. In which, the empty row message (“No records to display”) is always shown in the frozen part if the frozen columns existed in the Grid.

If you like to display the text in the movable content, you can achieve your requirement by using the dataBound event of Grid. So, we suggest you follow the below way to achieve your requirement.

![image](https://user-images.githubusercontent.com/57442688/116540633-0db91d00-a908-11eb-8f41-6f1186cde1c0.png)

Sample: https://stackblitz.com/edit/angular-low5vm-r5hzun?file=app.component.ts

API: https://ej2.syncfusion.com/angular/documentation/api/grid/#databound

        https://ej2.syncfusion.com/angular/documentation/api/grid/#currentviewdata


Screenshot:

![image](https://user-images.githubusercontent.com/57442688/116540752-317c6300-a908-11eb-820e-6b4ed8c62e45.png)

Regards,
Rajapandi R
