### ISSUE TITLE
Basic gantt failure

### ISSUE THREAD

**Issue by duzenko** [syncfusion/ej2-angular-ui-components#167]
Trying to reproduce the issue I have in my business app, I can't get even a minimal gannt app working

![image](https://user-images.githubusercontent.com/1481807/115238320-3a11b400-a126-11eb-8368-2187dafae521.png)

https://stackblitz.com/edit/gantt-issuse-sample-jfqwdf?file=package.json

**Comment by MonishaSivanthilingam** [comment]
Hi duzenko,

Greetings from Syncfusion support.

We have analyzed the sample project you shared. We noticed that you have not mapped the task fields in the sample project you shared. That is the reason for the error. In Gantt chart it is important to map the task fields as the Gantt Chart is rendered based on them.

We have modified your sample to include these changes. Please find the modified sample from the below link.

**Sample:** https://stackblitz.com/edit/gantt-issuse-sample-k7umlw?file=app.component.ts

Please refer the below documentation link for more information. 
 
**Online Documentation:** https://ej2.syncfusion.com/angular/documentation/gantt/getting-started/#mapping-task-fields 
 
Please contact us if you require any further assistance. 
 
Regards, 
Monisha.
