### ISSUE TITLE
PivotChart: PrimaryXAxis labelStyle not being applied

### ISSUE THREAD

**Issue by stephkoltun** [syncfusion/ej2-angular-ui-components#170]
It seems that the label style is not being applied to the `primaryXAxis`.  The font style is showing as Arial for the Y axis, but is not appearing for the _label_ text on the X axis.

[Stackblitz link](https://stackblitz.com/edit/angular-nqremp-xchhtd?file=app.component.ts)

My chart settings are:
```
this.chartSettings = {
      title: "Sales Analysis",
      chartSeries: { type: "Column" },
      primaryYAxis: {
        labelStyle: { fontFamily: 'Arial', fontWeight: '400' },
        titleStyle: { fontFamily: 'Arial', fontWeight: '400' }
      },
      primaryXAxis: {
        isIndexed: true,
        tickPosition: "Inside",
        labelIntersectAction: "Hide",
        enableTrim: true,
        tabIndex: 1,
        labelStyle: { fontFamily: 'Arial', fontWeight: '400' },
        titleStyle: { fontFamily: 'Arial', fontWeight: '400' }
      }
    } as ChartSettings;
```

![Screen Shot 2021-04-30 at 11 23 54 AM](https://user-images.githubusercontent.com/7053425/116717140-94243c00-a9a6-11eb-8acc-b87a2eb2c20f.png)

**Comment by maniram21** [comment]
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/MANIKA~2/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel="themeData" href="file:///C:/Users/MANIKA~2/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/MANIKA~2/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>






<p class="MsoNormal">Hi <span style="color:black;letter-spacing:.2pt;background:
white">Stephanie Koltun</span>,<span style="letter-spacing:.2pt;background:
white"><o:p></o:p></span></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal">We are glad to inform you that the weekly release
(v19.1.0.67) has been rolled out and we have provided “<b><span style="color:black;letter-spacing:.25pt;background:white">Event support for
multi-level labels</span></b>”. Kindly refer the following code example and
sample.<o:p></o:p></p>

<p class="MsoNormal"><b>Code Example:<o:p></o:p></b></p>


axisMultiLabelRender(args:&nbsp;IAxisMultiLabelRenderEventArgs):&nbsp;void&nbsp;{   &nbsp;&nbsp;&nbsp;&nbsp;args.textStyle&nbsp;=&nbsp;{   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fontFamily:&nbsp;'Arial',   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fontWeight:&nbsp;'bold',   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fontStyle:&nbsp;'italic',   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size:&nbsp;'10px',   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color:&nbsp;'grey'   &nbsp;&nbsp;&nbsp;&nbsp;};   &nbsp;&nbsp;}   &nbsp;   &nbsp;&nbsp;/*&nbsp;tslint:disable&nbsp;*/   &nbsp;&nbsp;ngOnInit():&nbsp;void&nbsp;{   &nbsp;&nbsp;&nbsp;&nbsp;this.chartSettings&nbsp;=&nbsp;{   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;'Sales&nbsp;Analysis',   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chartSeries:&nbsp;{   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type:&nbsp;'Column'   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axisMultiLabelRender:&nbsp;this.axisMultiLabelRender.bind(this)   &nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;as&nbsp;ChartSettings;   &nbsp;&nbsp;}   }
--




<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal"><b>Sample:</b> <a href="https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Fangular-4vhm1k%3Ffile%3Dapp.component.ts&amp;data=04%7C01%7Cmanikandan.murugesan%40syncfusion.com%7C128838a8678546fcba0408d92a7f430b%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637587548333850840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=kI9KUURGQlZ1RplXZKNeV0m%2BJV1fYQxw6foijaJQEJw%3D&amp;reserved=0">https://stackblitz.com/edit/angular-4vhm1k?file=app.component.ts</a><o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal">We thank you for your support and appreciate your patience
in waiting for this release. Please contact us if you would require any further
assistance.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal">Regards,<o:p></o:p></p>

<p class="MsoNormal">Manikandan<o:p></o:p></p>
