### ISSUE TITLE
bind new datasource on dropdown change event - ejs schedule event component

### ISSUE THREAD

**Issue by codeflashinfotech** [syncfusion/ej2-angular-ui-components#172]
I am trying to implement a dropdown on the change method inside the event modal. I have added the change event into the first dropdown and the method is also called but the data source of the second dropdown is not updating.

Can anyone faced this issue or implement it like this then please suggest the solution?

TIA

**Comment by Nevitha-Ravi** [comment]
Dear Customer,

Greetings from Syncfusion Support..!

We have validated your shared query at our end and suspect that your requirement is to perform cascading DropDownList is a series of DropDownList, where the datasource of one DropDownList depends upon another’s value. And for the same, we have prepared a sample using the poupOpen event of our Scheduler, which can be viewed from the following link.

Sample: https://stackblitz.com/edit/angular-customized-cascading-dropdowns-sample?file=app.component.ts
UG link: https://ej2.syncfusion.com/documentation/drop-down-list/how-to/cascading/

Kindly try the above solution and get back to us if you need any further assistance.

We will be happy to assist you..!

Regards,
Nevitha

**Comment by codeflashinfotech** [comment]
Yes it works! <3
