### ISSUE TITLE
TypeError: Cannot call a class as a function in ejs-colorpicker

### ISSUE THREAD

**Issue by santoshnayak** [syncfusion/ej2-angular-ui-components#179]
I have imported the module 
import { ColorPickerModule } from '@syncfusion/ej2-angular-inputs';
in resppective module.
![image](https://user-images.githubusercontent.com/26774073/119788987-41c83380-bef0-11eb-922a-d7db0009cd33.png)

Then upon trying use 
    <input ejs-colorpicker type="color" id="colorpicker" />
![image](https://user-images.githubusercontent.com/26774073/119789063-54db0380-bef0-11eb-8291-ea9e6a011acd.png)

i am facing error
TypeError: Cannot call a class as a function

![image](https://user-images.githubusercontent.com/26774073/119788917-31b05400-bef0-11eb-9d8d-dc2ab78e2d2b.png)

**Comment by Aravin06** [comment]
Hi Santoshnayak,

We have checked your query in our latest Syncfusion Angular Input control version 19.1.63. We cannot reproduce your reported issue in our end. For your reference we have prepared video demo and sample.

Demo: https://www.syncfusion.com/downloads/support/directtrac/general/ze/ColorPicker456024610 

app.moudule.ts
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
// Importing Colorpicker module from Syncfusion ej2-angular-inputs package.
import { ColorPickerModule } from '@syncfusion/ej2-angular-inputs';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,ColorPickerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

app.component.html
`<input ejs-colorpicker type="color" id="colorpicker" />`

styles.css
`@import "../node_modules/@syncfusion/ej2-base/styles/material.css";
@import "../node_modules/@syncfusion/ej2-buttons/styles/material.css";
@import "../node_modules/@syncfusion/ej2-popups/styles/material.css";
@import "../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css";
@import "../node_modules/@syncfusion/ej2-inputs/styles/material.css";
`

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/my-app-1959040593 

If you are still facing the issue, kindly share the below details.

•	If possible, try to reproduce the reported issue in provided sample or share the issue reproducible sample.
•	Please share us the video demonstration of this issue.
•	Please share us the Essential Studio Product Version.
•	Please let us know if you are using customization in ColorPicker.

Please provide the above requested information, based on that we will check and provide you a better solution quickly.

Regards,
Aravinthan S
