### ISSUE TITLE
Scroll the screen when date-range picker open

### ISSUE THREAD

**Issue by anoopyadav-kiwi** [syncfusion/ej2-angular-ui-components#18]
Hello Team,

I want to scroll the screen when the date-range picker is open. Below is the sample link of my requirement. Please note that I'm using the date-range picker not date picker.
[date-range-picker.mov.zip](https://github.com/syncfusion/ej2-angular-ui-components/files/3078597/date-range-picker.mov.zip)

Thanks in Advance.

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

Greetings from Syncfusion.

We have checked the provided video and we would like to inform you that, DateRangePicker popup will be opened based on the available space from the input of the DateRangePicker in the page. If enough space is available, then popup will be rendered below the input if space is not enough then popup will be rendered above the input. If space is not enough in both the positions (above and below), then popup will be opened with scroller. This is the default behavior of the DateRangePicker component. 

Please find the sample from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-rj4p1s-wbjtlt?file=app.component.html 

If we misunderstood your query, please revert with your exact scenario or a sample to proceed further.

Regards,
Berly B.C

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and provided an update for query.
