### ISSUE TITLE
It can not use two document editor components in one parent component.

### ISSUE THREAD

**Issue by hinhle** [syncfusion/ej2-angular-ui-components#180]
HTML elements in document editor have an id property. When using more than one document editor component in one parent component, the app raises warnings:

![image](https://user-images.githubusercontent.com/56920722/120137696-1189d900-c1ff-11eb-8e76-3d46ff53908c.png)

After destroying the component that contains two document editor components and then whenever I click anywhere on the app page, the app shows this error:

![image](https://user-images.githubusercontent.com/56920722/120137813-54e44780-c1ff-11eb-82aa-0d47eb527741.png)

**Comment by kurthisBanu** [comment]
Hi Team,

We are cross your reported issue. We suspect the issue because of you have used same ID for two documenteditor. Please create unique Id for each documenteditor component.

Please let us know if you still facing issue.

Regards,
Kurthis Banu A.

**Comment by hinhle** [comment]
The issue happens because of duplicated ids in sub-components of document editors like buttons or inputs. So, how can setting ID for document editor <ejs-documenteditorcontainer> component fix the issue?

Thanks.

**Comment by kurthisBanu** [comment]
Hi hinhle,

Kindly refer the below code snippet for your requirement.

<div>
 
<ejs-documenteditorcontainer **#documenteditor_default** [enableToolbar]=true [locale]="culture" (created)="onCreate()" (documentChange)="onDocumentChange()" height="600px" style="display:block;"></ejs-documenteditorcontainer>


             <ejs-documenteditorcontainer **#documenteditor_subset** 
height="600px" style="display: block;"></ejs-documenteditorcontainer>

</div>

Refer the below sample link also.

Sample Link:
https://stackblitz.com/edit/angular-gmtoko-jvrvrc?file=app.component.html

Regards,
Kurthis Banu A.
