### ISSUE TITLE
"Cannot read property 'unsubscribe' of undefined" error when ejs-grid is destroyed

### ISSUE THREAD

**Issue by siamcr7** [syncfusion/ej2-angular-ui-components#185]
It seems after upgrading to the latest version (19.2.47) of ejs-grid, whenever the grid (with filter type set as "Excel") is destroyed a JavaScript exception with the following error message is thrown:
"Cannot read property 'unsubscribe' of undefined"

I have added a StackBlitz demo [here](https://stackblitz.com/edit/angular-hk4xrf?file=app.component.ts).
You can click on the button to reproduce the issue on the console. 

Please note that this SB example was created from the demo section.

A few points to note here:
- We want to enable sorting and filter in the grid at the same time
- We want to have the sorting type as "Excel"

**Comment by Ajithbala** [comment]
Hi Customer, 

Thanks for the patience. 

Query: Query: It seems after upgrading to the latest version (19.2.47) of ejs-grid, whenever the grid (with filter type set as "Excel") is destroyed a JavaScript exception with the following error message is thrown: "Cannot read property 'unsubscribe' of undefined" I have added a StackBlitz demo 
 
We have checked you attached sample with the latest Syncfusion package versions and found everything works fine at our end. So, for your convenience we have attached the sample, please refer them for your reference. 

Sample Link: https://stackblitz.com/edit/angular-hk4xrf-g53rla?file=app.component.ts 

Query: A few points to note here: - We want to enable sorting and filter in the grid at the same time - We want to have the sorting type as "Excel" 
 
Based on your query you want to have the sorting type as "Excel" in your Grid application.  So, before we proceed to your query, please share the below details to validate further on your requirement. 

Please explain your exact requirement that you want to achieve in your Grid application.

Please explain more details on the query We want to enable sorting and filter in the grid at the same time - We want to have the sorting type as "Excel".
 
Do you want to perform the sorting operation when you perform the filtering?

 
Regards, 
Ajith G.

**Comment by siamcr7** [comment]
Hi Ajith,

Yes. We would like to have sorting and filtering enabled for the columns in the grid. Please see the image below for more details:
![image](https://user-images.githubusercontent.com/9120305/127123362-859c803c-026e-40bf-85f8-34ffa4dc7fea.png)

**Comment by Ajithbala** [comment]
Hi Customer,

Thanks for the update.

Query: Yes. We would like to have sorting and filtering enabled for the columns in the grid. Please see the image below for more details:

Based on the attached screenshot and query, you want to use the excel filter with sorting options for the columns in your Grid application. By default, in our EJ2 Grid when you enable the excel filter with sorting,  the filter dialog will have both sorting and filtering options.

You can enable the excel filter by setting the type as Excel in the filterSettings of the Grid component and you can enable the sorting by setting the allowSorting property as true. For your convenience we have attached the sample, please refer them for your reference. 

`  public ngOnInit(): void {
    this.data = getData(1000);
    this.filterSettings = { type: 'Excel' };
    this.filter = { type: 'Excel' };
    this.stTime = performance.now();
    this.selectionSettings = {
      persistSelection: true,
      type: 'Multiple',
      checkboxOnly: true
    };
  }
`

`  <ejs-grid #overviewgrid id='overviewgrid' [dataSource]='data' rowHeight='38' [allowSelection]='true'
        [allowSorting]='true' height='600' (dataBound)='onDataBound($event)' [enableHover]='false'
        [selectionSettings]='selectionSettings' [filterSettings]='filterSettings' [allowFiltering]='true'
        [enableVirtualization]='true'>
        <e-columns>
            <e-column type='checkbox' [allowFiltering]='false' [allowSorting]='false' width='60'></e-column>
            <e-column field='EmployeeID' [visible]='false' headerText='Employee ID' width='130' [isPrimaryKey]='true'>
            </e-column>
            <e-column field='Employees' headerText='Employee Name' [filter]='filter' clipMode='EllipsisWithTooltip'
                width='200'>
`

Sample Link: https://stackblitz.com/edit/angular-hk4xrf-qf8bs7?file=app.component.ts

UG-links: https://ej2.syncfusion.com/angular/documentation/grid/filtering/#excel-filter

Please get back to us if you need further assistance.

Regards,
Ajith G.

**Comment by gsumankumar** [comment]
We have closed this issue now, since there's no recent activities. You can reopen it, if you have any queries on this issue.
