### ISSUE TITLE
Copy paste from MS office missing a line and format changes_Limitation of Angular rich text editior???

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#186]
Dear Team,
Synfusion team not taken this issues as serious or neglecting this issues purposefuly.
**_Copy past from attached word into Angular rich text editor changing the bullet point and **Red marked lines** in the word file is getting missed._** please refer all attached images and please check and kindly give importance.
Additional References : working fine with Reactjs and vue js Richtext editor

Both attached images are from global demo and our app . compare with attached word file content.
![copy past from word to angular Global website demo](https://user-images.githubusercontent.com/63642104/125905590-ba1e1cb6-89b2-4805-82ff-85bd8059cc87.PNG)

![copy paste word to rich text editotor- angular v 19 2 47](https://user-images.githubusercontent.com/63642104/125904743-83f846ad-9ad1-45a2-8ebb-0bfffefa282f.PNG)
[aaa corads 5 LN_KINS COPY_copy past issues with Angular rich text editor.docx](https://github.com/syncfusion/ej2-angular-ui-components/files/6828440/aaa.corads.5.LN_KINS.COPY_copy.past.issues.with.Angular.rich.text.editor.docx)

**Comment by arunjoshtech** [comment]
Dear @Mydeen-SN please update possible solution for this issues.

**Comment by arunjoshtech** [comment]
@Mydeen-SN Did you tested with given Ms office doc? Can I expect any news about it? Do you need any live demo on this issues?

**Comment by gunasekar-kuppusamy** [comment]
Hi Arun,

Greetings from Syncfusion support.

We have validated your query and we have considered “Provide support to paste rare list content from MS Word to the Rich Text Editor” as a feature from our end and logged the report for the same and it will be included in our Volume 2 SP1 release scheduled on the second week of August.

You can now track the current status of the report, review the proposed resolution timeline, and contact us for any further inquiries through this link: https://www.syncfusion.com/feedback/27130


Regards,
Gunasekar

**Comment by arunjoshtech** [comment]
Dear Ginasekar,
Thanks for consideration and Confirmation. 
Note : This feature already exist in vuejs and Rectjs rich text editor.

**Comment by gunasekar-kuppusamy** [comment]
Hi Arun,

We are glad to announce that our Essential Studio 2021 Volume 2 SP release v19.2.0.55 is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/168015/essential-studio-2021-volume-2-service-pack-release-v19-2-0-55-is-available-for-download

We have included the feature  **"Provide support to paste rare list content from MS Word to the Rich Text Editor”.** Can you please upgrade your package version to the latest to resolve the issue from your end? 

**Release notes:** https://ej2.syncfusion.com/angular/documentation/release-notes/19.2.55/?type=all#richtexteditor

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,          
Gunasekar

**Comment by arunjoshtech** [comment]
Dear Team,
It is been fixed and thanks for the work and attention given.
