### ISSUE TITLE
RichTextEditor has no exported member 'ɵɵFactoryDeclaration'.

### ISSUE THREAD

**Issue by davidzr** [syncfusion/ej2-angular-ui-components#188]
Hello, I'm triying to install ej2-angular-richtexteditor but I get the following error after installation: 

````Error: node_modules/@syncfusion/ej2-angular-richtexteditor/node_modules/@angular/common/common.d.ts:1279:25 - error TS2694: Namespace '"node_modules/@syncfusion/ej2-angular-richtexteditor/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

1279     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<LocationStrategy, never>;
                             ~~~~~~~~~~~~~~~~~~~~
Error: node_modules/@syncfusion/ej2-angular-richtexteditor/node_modules/@angular/common/common.d.ts:1304:25 - error TS2694: Namespace '"node_modules/@syncfusion/ej2-angular-richtexteditor/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

1304     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<LowerCasePipe, never>;
                             ~~~~~~~~~~~~~~~~~~~~
Error: node_modules/@syncfusion/ej2-angular-richtexteditor/node_modules/@angular/common/common.d.ts:1305:26 - error TS2694: Namespace '"node_modules/@syncfusion/ej2-angular-richtexteditor/node_modules/@angular/core/core"' has no exported member 'ɵɵPipeDeclaration'.

1305     static ɵpipe: ɵngcc0.ɵɵPipeDeclaration<LowerCasePipe, "lowercase">;
````

**Versions**

Angular 12.1.0
ej2-angular-richtexteditor 19.2.49

**Comment by VinithaJeyakumar** [comment]
Hi David,


We have validated your query “**RichTextEditor has no exported member 'ɵɵFactoryDeclaration'** ”

We suspect that the issue will be resolved by clearing the cache and removing the “**node_modules**”, “**package_lock.json**” files completely, and reinstalling them. 
 
**Documentation**: https://ej2.syncfusion.com/angular/documentation/common/how-to/update-npm-package/ 
 
Please ensure the issue after the above suggestions are done. If the issue still occurs, can you share the following details? 

•	The NPM version you have configured in your application.
•	If possible, please share us with the simple runnable issue reproducing sample.

The above details will be helpful for us to assist you at the earliest. 
 
Regards 
Vinitha

**Comment by davidzr** [comment]
Hi,

I downgrade from node v16 to node v14 and now it works.

Thanks!
