### ISSUE TITLE
"ERROR TypeError: Cannot read property 'setAttribute' of null" when ejs-multiselect item is selected when the [mode]="'CheckBox'"

### ISSUE THREAD

**Issue by ahsanromeo** [syncfusion/ej2-angular-ui-components#189]
It seems the item checkboxes are not rendered and when ejs-multiselect item is selected with the [mode]="'CheckBox'", "ERROR TypeError: Cannot read property 'setAttribute' of null" error is thrown.

I am attaching a StackBlitz demo [here](https://stackblitz.com/edit/angular-ivy-heflfx)
The ej2-angular-dropdowns version is 19.2.51

You can click on the "Select Games" to show the dropdown. Then click on an item to get the console error.

 I am also attaching a screenshot of the error.
![error](https://user-images.githubusercontent.com/9861470/128680050-20d3d623-5b31-4580-bd31-f29db173e4c7.JPG)

**Comment by SevvandhiN** [comment]
Hi Ahsanromeo,


In the sample, you have to include MultiSelectAllModule for rendering checkbox in the app.module.ts file. Please refer the modified sample below.


Sample link: https://stackblitz.com/edit/angular-ivy-rcmm4z


Kindly get back to us for further assistance.


Regards,
Sevvandhi N

**Comment by ahsanromeo** [comment]
Thank you. We were able to fix the issue with the assistance of your suggestion.
