### ISSUE TITLE
Auto Capital and spelling correction features

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#190]
Dear Team, 
How to enable auto Caps and Auto corrections in Angular Rich text editor. Kindly advise.
IF there is no possibilities kindly inform so that I will remove this issues by closing it

**Comment by VinithaJeyakumar** [comment]
Hi Arun,


Greetings from Syncfusion support


We have validated your queries,

Query 1. “**Auto Capital feature**”

We have logged the requested requirement as a feature at our end. This support will be included in any one of our upcoming releases. We will intimate you once the road map has been prepared.

Please track the status of the reported feature request from the below feedback.

**Feedback Link**: https://www.syncfusion.com/feedback/27936/provide-auto-capital-support-with-rich-text-editor 

Query 2. “**Auto corrections feature**”

We have logged the requested requirement as a feature at our end. This support will be included in any one of our upcoming releases. We will intimate you once the road map has been prepared.

Please track the status of the reported feature request from the below feedback.

**Feedback Link**: https://www.syncfusion.com/feedback/27935/provide-auto-correct-support-with-rich-text-editor 

Regards,
Vinitha.

**Comment by arunjoshtech** [comment]
Dear Vanitha,
Really thanks for considering our request and taking the product one step ahead.
