### ISSUE TITLE
How can I add mandatory symbol * with red color

### ISSUE THREAD

**Issue by EVNIKHIL** [syncfusion/ej2-angular-ui-components#198]
Hi I am using the syncfusion ejs datepicker for my project. 
`<ejs-datepicker
                                            [formControl]="dueDate"
                                            [allowEdit]="false"
                                            name="dueDate"
                                            floatLabelType="Auto"
                                            openOnFocus="true"
                                            [showTodayButton]="false"
                                            format="{{ dateTimePickerFormat?.date }}"
                                            [min]="tomorrow"
                                            placeholder="{{ 'INVO_COMMON_DUEDATE' | translate }}"
                                            id="invoice-save-invoice-due-date"
                                            (change)="dateChanged()"
                                            ngDefaultControl
                                        ></ejs-datepicker>` Like this and I need to mark this date picker as mandatory with * in red color. How can achieve that?. Please help

**Comment by Deepak-Ramakrisnan** [comment]
Hi Evnikhil,

Greetings from Syncfusion support.

Yes we can override the existing styles of the datepicker floatlabel and we can add the customized content to it.Please refer the below highlighted code and sample for your reference.

```
.e-input-group.e-control-wrapper.e-float-input .e-float-text::after{
    **content: "*";
    color: red;**
}


```

**Sample Link** :  https://stackblitz.com/edit/angular-dvggnz?file=app.component.css

Kindly revert us if you have any concerns in it.

Thanks,
Deepak R.
