### ISSUE TITLE
Define columns from component 

### ISSUE THREAD

**Issue by akamal88** [syncfusion/ej2-angular-ui-components#20]
Can i define columns from component since i am loading those columns via api, also, each column has different template such as SVG, numbers, texts, dates...

**Comment by bharathm03** [comment]
@akamal88 can you please share the component name that you are using? It will be helpful in replying your query.

**Comment by akamal88** [comment]
@bharathm03 Thanks, i meant the data grid

**Comment by jvhariharan** [comment]
We have an option to display the number, text and date values and custom values in grid columns. If you want to use a custom template like SVG then we suggest you to use the column template feature to achieve your requirement.

We have prepared a sample for your reference. Please refer to the below sample and documentation for more information.

Sample : https://stackblitz.com/edit/angular-gbqvtt-213wxr?file=app.component.html 

Demo sample : https://ej2.syncfusion.com/angular/demos/#/material/grid/column-template

Help documentation : https://ej2.syncfusion.com/angular/documentation/grid/columns/?no-cache=1#column-template

**Comment by akamal88** [comment]
Nice, thank you

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution already provided.
