### ISSUE TITLE
Peer dependencies are out of sync with latest Angular version (12.2.11)

### ISSUE THREAD

**Issue by ajlouie** [syncfusion/ej2-angular-ui-components#200]
I'm getting these peer dependency warnings from npm when upgrading to Angular 12.2.11:
<img width="1472" alt="Screen Shot 2021-10-27 at 11 57 46 AM" src="https://user-images.githubusercontent.com/4656575/139102664-1aa583cb-e97c-4883-a021-334b83f01919.png">

The [peer dependencies for the  latest release (19.3.47)](https://github.com/syncfusion/ej2-angular-ui-components/blob/v19.3.47/components/base/package.json#L18-L25) only go up to Angular version 12.2.8.

**Comment by GOKUL3897** [comment]
Hi Ajlouie,  
  
Thanks for your patience. 
 
We would like to let you know that we have resolved the peer dependency warnings in our latest package. The changes will be available from our latest package which is the 19.3.44 version.  
  
https://ej2.syncfusion.com/angular/documentation/release-notes/19.3.44/?type=all#common  
  
Regards,  
Gokul
