### ISSUE TITLE
Word processor Document editor Not for real world doc work

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#202]
Dear Team
Word editor is not supportive for real world uses.
copy past from word to web showing a Loading animation and taking more than 5 to 30 seconds some time 5 minutes
Copy past within the doc editor also showing loading animation and taking more time as above said.
is it just beta version? how to enable instant Copy paste from Word or first paragraph content to third para without loading animation.

**Comment by kurthisBanu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/KURTHI~2/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/KURTHI~2/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/KURTHI~2/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in;word-wrap:
break-word'>


<p class=MsoNormal>Hi arunjoshtech,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Syncfusion Greetings!&nbsp;&nbsp;&nbsp;<o:p></o:p></p>

<p class=MsoNormal>&nbsp;&nbsp;<o:p></o:p></p>



Queries | Solution
-- | --
copy past   from word to web showing a Loading icon and taking more than 5 to 30 seconds. | For your   information, when copy and paste content from outside the editor using online   demo web service URL('https://ej2services.syncfusion.com/production/web-services/api/documenteditor/’)   which is for demo purpose, it will paste content based on Internet   connection and size of the content which you were trying to paste.       If were you   local configured service, by creating your own web service, like below:       https://github.com/SyncfusionExamples/EJ2-Document-Editor-Web-Services       It will paste   content without internet connection.        Process:        To copy and   paste, we will send the clipboard content to server side and process it in   back end, then back end will return the sfdt string. Document Editor insert   it in client side.           Can you   please confirm whether you were using online web service or local service?
Copy past within the doc editor also showing loading   animation , how to enable instant Copy paste from Word or first   paragraph content to third para without loading animation. | To copy/   paste within or outside control, it will show loading animation to indicate   the progress is going on.       If you want   to copy/paste within control, you can use EnableLocalClipboard property.        By enabling EnableLocalClipboard   paste property, which allows you to cut/copy and paste content within   control. This property default value is false. You can enable this   property using, built-in toolbar options.           Code snippet:                   <ejs-documenteditorcontainer #documenteditor_default [enableToolbar]=true [enableLocalPaste]=true       [locale]="culture" (created)="onCreate()" height="600px" style="display:block;"></ejs-documenteditorcontainer>                    Documentation link:      https://ej2.syncfusion.com/angular/documentation/document-editor/clipboard/#local-paste       Document   editor requires server-side interaction to copy and paste content with   formatting from outside of editor, you have to set enableLocalPaste   as false and you must create own web service to paste the content, like   below:       https://github.com/SyncfusionExamples/EJ2-Document-Editor-Web-Services        // Run the web service then   replace the service URL by running local URL.     container.documentEditor.serviceUrl   ="http://localhost:62870/api/documenteditor/" | <ejs-documenteditorcontainer #documenteditor_default [enableToolbar]=true [enableLocalPaste]=true       [locale]="culture" (created)="onCreate()" height="600px" style="display:block;"></ejs-documenteditorcontainer>
<ejs-documenteditorcontainer #documenteditor_default [enableToolbar]=true [enableLocalPaste]=true       [locale]="culture" (created)="onCreate()" height="600px" style="display:block;"></ejs-documenteditorcontainer>
is it just   beta version? | Could you   please share Syncfusion product version which you are using in your   application?       Thereby, we   will proceed further on the reported issue and provide you the appropriate   solution at the earliest.



<p class=MsoNormal>&nbsp;<o:p></o:p></p>

<p class=MsoNormal>Please let us know if you have any other questions.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Regards,<o:p></o:p></p>

<p class=MsoNormal>Kurthis Banu A.<o:p></o:p></p>


</body>

</html>

**Comment by arunjoshtech** [comment]
Dear Banu,
Appreciate your proper explanation.
Meantime few updates released a day before and resolved file opening contains table and other major errors.
We are using latest Versions to mock up the user case.
1.This is Web application and we are looking to integrate but we are struggling to manage the copy paste.Copy  paste from Inside editor or out side editor works  with keyboard short cut (CTRL+V) , but mouse right click shows as disabled.
2. If we host your api in our server will it perform better ?
3. Top tools are very bigger in size hold major area of screen so the document view area become small.
![synfusion area](https://user-images.githubusercontent.com/63642104/141816825-fc6eb6c1-980f-4ce6-80a2-a39196236678.PNG)

**Comment by arunjoshtech** [comment]
Dear Team, 
Another major clarification needed on copy paste inside the word editor using mouse is not enabled. in your demo itself.

I have copied the first paragraph using mouse right click function then I want to page the same paragraph in second page, so when I place cursor and right click the mouse it shows paste disabled.
Please make sure user interface using mouse and keyboard short cuts are most important to use this word editor. looking forward your reply.
Thank you

**Comment by kurthisBanu** [comment]
Hi arunjoshtech, 

Regarding: Context Menu (mouse right click function)

If you want to copy/paste within control, you can use EnableLocalClipboard property.  

For your better understanding we have attached video demonstration in below link 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/LocalPaste-679320884 
 
Documentation link:    
https://ej2.syncfusion.com/react/documentation/document-editor/clipboard/#local-paste 
 
https://ej2.syncfusion.com/react/documentation/document-editor/clipboard/#paste-with-formatting 

Regarding: Top tools are very bigger in size hold major area of screen, so the document view area become small.

DocumentEditorContainer is a predefined component which wraps DocumentEditor, Toolbar, Properties pane, and Status bar into a single component. And the toolbar and properties pane is used to view and modify the document in DocumentEditor thought public APIs available in it. 
 
Documentation Link: 
https://ej2.syncfusion.com/angular/documentation/document-editor/getting-started/#documenteditorcontainer-component 

DocumentEditor Component is used to create, view and edit word documents. In this, you can customize the UI options based on your requirements to modify the document.    
 
 
 
Documentation Link: 
https://ej2.syncfusion.com/angular/documentation/document-editor/getting-started/#documenteditor-component 


If we host your api in our server, will it perform better?

Yes, you can able host our webservice based on your requirement.

Regards,
Kurthis Banu A.

**Comment by arunjoshtech** [comment]
Thanks for the detailed reply.
