### ISSUE TITLE
Copy Paste using Mouse is not working_ Word editor

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#205]
Dear Team,

I have copied Ms word content using mouse right click function then I came to Word editor to paste it. When I click Right mouse button it shows "Paste" is disabled. But the content get pasted using with keyboard short cut Ctrl+V.

In your demo also found the same. kindly advise

**Comment by Suriya-Murugan** [comment]
Hi Arunjoshtech,

By default, context menu paste is disabled in Documenteditor. Retrieving the data from system clipboard in an automated way through script/code is denied as a part of browser security policy. In Document editor, we use our own context menu to display the Word editor specific menu items. So, retrieving the data from system clipboard through onclick event of our own context menu item is not possible and the paste option is in disabled state by default in Document editor.   

Whereas the browser’s native paste operation from system clipboard will work only on the user’s direct interaction like, keyboard shortcut ‘CTRL + V’ or browser’s built-in context menu paste option click. 
  
Hence, it is not possible to paste content from outside Document editor using context menu’s paste option. Use keyboard shortcut ‘CTRL + V’ which gets the data from system clipboard and pastes content to Document editor. 
  
Document editor provides an alternate solution to copy/cut and paste content within Document editor using context menu’s paste option. You can set [enableLocalPaste](https://ej2.syncfusion.com/angular/documentation/document-editor/clipboard/#enablelocalpaste-behaviour   ) property to true, to get this alternate solution working. By default this property is false.  
https://ej2.syncfusion.com/angular/documentation/document-editor/clipboard/#enablelocalpaste-behaviour 

Regards,
Suriya M.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
