### ISSUE TITLE
The slow rendering of the angular document editor.

### ISSUE THREAD

**Issue by hinhle** [syncfusion/ej2-angular-ui-components#206]
Dear Team,

When I open a component containing the document editor component, it appears to be that the document editor component rendering finishes more slowly than the parent component does. But that does not happen in all of the components containing it.

Thanks.

![image](https://user-images.githubusercontent.com/56920722/142582858-1fb936e4-ee88-48a9-adef-3e85746f71ba.png)

![image](https://user-images.githubusercontent.com/56920722/142584575-a8c01b41-aa26-4fe3-bb22-2bbf351568a5.png)

**Comment by Suriya-Murugan** [comment]
Hi Hinhle,

Can you please try the reported issue in the latest version and let us know if you still facing issues regarding this with the simple sample? That will be helpful for us to proceed further and provide you with the solution at the earliest.

Regards,
Suriya M.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
