### ISSUE TITLE
Display different colors on multi schedule for same date

### ISSUE THREAD

**Issue by 123pappu** [syncfusion/ej2-angular-ui-components#209]
Hello 

Can you please let me know 
How to display event in  different colors text if the there is multi events on same date

https://prnt.sc/20xkgp7

**Comment by VengateshManiraj** [comment]
@123pappu You can display the events in different text colors with the help of eventRendered event like below code.

app.component.html
```

<ejs-schedule
      #scheduleObj
      width="100%"
      height="650px"
      [selectedDate]="selectedDate"
      [eventSettings]="eventSettings"
      [(currentView)]="scheduleView"
      (eventRendered)="onEventRendered($event)"
    >
```

app.component.ts
```
 public onEventRendered(args: EventRenderedArgs): void {
    if (this.scheduleObj.currentView === 'Month' && args.data.Index > 0) {
      (
        args.element.querySelector('.e-appointment-details') as HTMLElement
      ).style.color = 'red'; // here you can set your different color
    }
  }
```
You can find the same in the below sample 
https://stackblitz.com/edit/angular-srrvxh?file=app.component.html
