### ISSUE TITLE
Usage of ejs-grid component leads to memory leak 

### ISSUE THREAD

**Issue by egozavr** [syncfusion/ej2-angular-ui-components#21]
## There is a leaky problem

Here is example: https://stackblitz.com/edit/angular-ejs-grid-memleak

Clicking on button toggles `HelloComponent` init/destroy (which may be seen in devtools console). `HelloComponent` template includes `ejs-grid`:
```html
<h2>Grid here</h2>
<ejs-grid></ejs-grid>
```

Number on button (count of `HelloComponent` initializations) is the same as number of class instances in heap snapshot (garbage was preliminarily collected):

![image](https://user-images.githubusercontent.com/2705355/56510481-968b6a00-6532-11e9-864f-62dbce8f3a24.png)

**Comment by egozavr** [comment]
### Additional information

**All snapshots are filtered by `HelloComponent` class which is parent for `GridComponent`, see above. All snapshots are compared with the first one which doesn't include any instance of `HelloComponent`. Garbage is forcibly collected before every snapshot taken.**

- Step 0, just after application init:
![image](https://user-images.githubusercontent.com/2705355/56816338-03ad4100-684c-11e9-863f-274418adf6fb.png)
- Step 1, button clicked, hello component with grid inside initialized once;
![image](https://user-images.githubusercontent.com/2705355/56816485-4f5fea80-684c-11e9-8664-931e86eb4728.png)
- Step 2, button clicked, hello component destroyed by `*ngIf`, but its instance is still in memory:
![image](https://user-images.githubusercontent.com/2705355/56816719-cdbc8c80-684c-11e9-99da-ca58dec8f209.png)
- Step 3, button clicked, hello component initialized again, **new** instance is created, total 2 instances in memory:
![image](https://user-images.githubusercontent.com/2705355/56816845-052b3900-684d-11e9-80d1-183902bf6a44.png)
...
After series of `HelloComponent` init/destroy:
![image](https://user-images.githubusercontent.com/2705355/56817079-7cf96380-684d-11e9-95d9-7e31a84cda91.png)

Notice that without `GridComponent` instance of `HelloComponent` is removed from memory just after destruction, i.e. we observe either 0 or 1 instance at any any moment.

**Comment by egozavr** [comment]
Update packages up to 17.2.39 version. The problem is still here. All that app does is just init and destroy component (`HelloComponent`), which contains GridComponent inside. After destoy where must be no references to `HelloComponent` in heap. And that's true if we don't use GridComponent. If we use one - references stay in heap.

**Comment by thavasianand** [comment]
Hi @egozavr ,

We have prepared a video demonstration on this issue we are not able to reproduce the issue. Please refer the below video sample for more information.

Video link : https://www.syncfusion.com/downloads/support/directtrac/253769/ze/Hellocomp-236496761.zip

Regards,
Thavasianand S.

**Comment by Remmo** [comment]
We have the same problem, all the pages with ejs-grid has memory leaks, if we remove the grid the memory leak gone

**Comment by thiyagu-subramani** [comment]
Hi @Remmo ,

We are glad to announce that in our patch release v18.3.52, we have included memory leak related issues. So kindly update your Syncfusion packages to our latest version v18.3.52 to resolve your query. 

Could you please follow the steps provided in the following documentation or use the below steps to update the packages

1.	Delete the package.lock.json file from your application.
2.	Remove the node_modules folder from your project.
3.	Use the current version (or use *)for all the Syncfusion components in the package.json file.
4.	Then do the npm install.

UG: https://ej2.syncfusion.com/angular/documentation/common/how-to/update-npm-package/

Also, use npm dedupe to remove the duplicate packages.

Still, if you face the same issue, share the following details to reproduce the reported behavior at our end.

1.	Share the package.json file.
2.	Share the full Grid rendering code.
3.	Share video/image representation of your issue.
4.	If possible, share the issue reproducible sample.

Please get back to us, if you need any further assistance.

Regards,
Thiyagu S

**Comment by ricardo-lobo** [comment]
This also happens with the ej2-vue-ui-components

**Comment by VigneshNatarajan27** [comment]
Hi @ricardo-lobo , 

Sorry for the delay in getting back to you. 

We understand that you are facing a memory leak issue in our Vue components. We have resolved the memory leaks issues in our latest version of Syncfusion packages. So kindly ensure the reported issue by upgrading to our latest version. If you are still facing the reported issue, kindly share the following details. 

1.	Are you facing issues in the Grid component or in any other components.   
2.	If yes, share the grid code example.
3.	Share more details on when you are facing the reported issue.
4.	Share details on the Memory tab. 
5.	If possible share a video demonstration of the issue.

It will be very helpful for us to validate the reported query at our end and provide a solution as early as possible. 
   
Regards,
Vignesh Natarajan

**Comment by syncsiva** [comment]
This issue has not had any activity for a week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
