### ISSUE TITLE
Draw back to back bar chart with Y axis (data label) in middle

### ISSUE THREAD

**Issue by hasan-enosis** [syncfusion/ej2-angular-ui-components#210]
![image](https://user-images.githubusercontent.com/58516749/144553160-136f1d02-5ef4-4c32-a5e5-c14186f73f23.png)

We want to draw a chart which looks exactly like above with Y axis (data label) in the middle and bars on both sides. We couldn't find any configuration or axes customization which could help us achieve that. Please let us know if there is a way in Angular Syncfusion to draw the above back to back bar chart exactly as it is.

**Comment by Arun-Raji** [comment]
Hi @hasan-enosis, 
 
Greetings from Syncfusion.
 
We can able to achieve your output by using the axis customization with the help of two bar charts with bootstrap column CSS. We have prepared a stackblitz angular sample to replicate your output in the below link and also attached the UG link of axis customization of angular charts.
 
UG link – https://ej2.syncfusion.com/angular/documentation/chart/axis-customization/
 
Sample - https://stackblitz.com/edit/angular-xzsh25?file=app.component.html
 
Output –
 
![Capture](https://user-images.githubusercontent.com/93248943/144840077-d3df3a25-091a-43ed-9424-68a43d4ef601.PNG)

 
Please let us know if you have any further clarification regarding this. 
 
Thanks,
Arun
