### ISSUE TITLE
Not all elements can be translated when appling different locale

### ISSUE THREAD

**Issue by MooDySmiles** [syncfusion/ej2-angular-ui-components#211]
Hello, I'm using `@syncfusion/ej2-angular-richtexteditor` and I wanted to change the tooltips and text displayed in Italian, but I don't seem able to properly change every tooltips and text in the Toolbar.

I'm using `L10n.load` method from `@syncfusion/ej2-base` as shown in the docs and in other GitHub issues this on the repo.

I'll leave a link to my repo on GitHub here: https://github.com/MooDySmiles/prova-richtext-editor as I'm not able to properly load a sample on StackBlitz, for some unknown reason to me whenever I try to add `RichTextEditorModule` to `app.module.ts` the app errors.

The files of interest are located in `src/app/features/text-editor`, I'm importing `RichTextEditorModule` from `@syncfusion/ej2-angular-richtexteditor` in the `text-editor.module.ts` file and trying to load Italian locale translation in `text-editor.component.ts` file.

I'm also using `Angular 13` but that doesn't seem to be the problem, as the application in the GitHub repo provided is correctly loading the editor with all its functiontalities.

**Comment by VinithaJeyakumar** [comment]
Hi,

We have tried to reproduce the reported issue from our end. but unfortunately, we didn't face any issues. we have also prepared a sample using localization for Italian language for your reference. please check the sample below,

**Sample**: https://stackblitz.com/edit/angular-rzpz78-jgt5qy?file=app.component.ts

Please check the below GitHub repository link for all the locale data of different cultures, 
**Link**: https://github.com/syncfusion/ej2-locale/blob/master/src/it.json

**Documentation**: https://ej2.syncfusion.com/angular/documentation/rich-text-editor/globalization/#localization

Regards,
Vinitha

**Comment by MooDySmiles** [comment]
Hi @VinithaJeyakumar,

Thank you, now is working as expected
