### ISSUE TITLE
Prevent Scroll when focusing in Angular Syncfusion Document Editor Container

### ISSUE THREAD

**Issue by hinhle** [syncfusion/ej2-angular-ui-components#212]
Hi Team,

I need the editor not to make the web page scroll when the focus event happens in the editor. But it seems like the library does not support for this option: 
![image](https://user-images.githubusercontent.com/56920722/145748433-9eeb508f-9792-42ce-8913-b2d74d945d33.png)

Thanks

**Comment by kurthisBanu** [comment]
Hi hinhle,

Document Editor doesn’t  have option to prevent the scroll bar. In Document Editor, we are using native scrollbar. 

Can we please let us know exact use case scenario regarding your requirement? that will be helpful for us to proceed further and provide you solution at earliest.

Regards,
Kurthis Banu A.

**Comment by hinhle** [comment]
Hi kurthisBanu,

Here is the example for my issue:

https://stackblitz.com/edit/angular-gmtoko-c6w4bp?file=app.component.html

Thanks

**Comment by Suriya-Murugan** [comment]
Hi Hinhle,

Apologies!

Can you please share the video illustration of the reported issue with details? that will be helpful for us to find the exact issue.

Regards,
Suriya M.

**Comment by Suriya-Murugan** [comment]
Hi Hinhle,

By default, we set focus to Documenteditor once control gets rendered. So, only page scrolls to the bottom.

We already logged the feature request to disable the autofocus in the Document editor. We will implement this feature in any of our upcoming releases. We will update the scheduled status of the below feedback link once it is taken for implementation. 
 
This feature can be tracked through below feedback links: 
https://www.syncfusion.com/feedback/22798/allow-disabling-of-auto-focus 

Please up-vote this feature request to make this feature request our priority.

You can also contact us through our [support forum](https://www.syncfusion.com/forums/), [Support Desk](https://support.syncfusion.com/), or [feedback portal](https://www.syncfusion.com/feedback/).

Regards,
Suriya M.

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. This feature can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/22798/allow-disabling-of-auto-focus
