### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by piotrroda** [syncfusion/ej2-angular-ui-components#215]
Hi.
I have updated do newest package 19.4.38, but still have warning like below.
In release notes for that version is that angular 13 is supported. https://ej2.syncfusion.com/angular/documentation/release-notes/19.4.38/?type=all#common

Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- @syncfusion/ej2-angular-richtexteditor [es2015/esm2015] (git+https://github.com/syncfusion/ej2-angular-ui-components.git)
- @syncfusion/ej2-angular-documenteditor [es2015/esm2015] (git+https://github.com/syncfusion/ej2-angular-ui-components.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by GOKUL3897** [comment]
Hi @piotrroda,

Sorry for the delay caused,

We have resolved your reported warning at our end. So, we are suggesting you use our latest version packages to avail those changes.

Regards,
Gokul
