### ISSUE TITLE
webpack warning

### ISSUE THREAD

**Issue by piotrroda** [syncfusion/ej2-angular-ui-components#216]
Hi.
After update to version 19.4.38 I get warning like below.

./node_modules/@syncfusion/ej2-navigations/styles/bootstrap.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].rules[0].oneOf[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rul
es[3].rules[0].oneOf[1].use[2]!./node_modules/@syncfusion/ej2-navigations/styles/bootstrap.css - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):

**Comment by axylophon** [comment]
I have the same problem

./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(9573:7) postcss-preset-env: end value has mixed support, consider using flex-end instead

**Comment by harrycollin** [comment]
Me too

**Comment by grascioni** [comment]
Same here

**Comment by GOKUL3897** [comment]
Hi All,

Sorry for the delay caused,

We have resolved your reported warning at our end. So, we are suggesting you use our latest version packages to avail those changes.

Regards,
Gokul
