### ISSUE TITLE
Auto capital After full stop in Rich text and Word Editor

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#218]
Dear Team,
Kindly advise how to enable Auto capitalization after full stop in a sentence for Rich text editor and Word editor

**Comment by VinithaJeyakumar** [comment]
Hi Arun,


Currently, we have not implemented this feature, we have already considered "**Provide Auto Capital support with Rich Text Editor** " as a feature and will implement in the certain release based on the customer request count and priority. So, we will intimate you once the road map has been prepared.

Please track the status of the reported feature request from the below feedback. 
 
**Feedback Link:** https://www.syncfusion.com/feedback/27936/provide-auto-capital-support-with-rich-text-editor

Please upvote this feature to make this our priority. We will prioritize the features every release, based on the user demands.

Regards,
Vinitha

**Comment by Suriya-Murugan** [comment]
Hi Arun,

We have logged this as a feature request in our database. We will implement this feature in any of our upcoming releases. We usually have an interval of at least three months between releases. The feature implementation would also greatly depend on the factors such as product design, code compatibility and complexity. We will update you when this feature has been implemented.

Please track the status of the reported feature request from the below feedback.
https://www.syncfusion.com/feedback/32427/auto-correct-options-like-microsoft-word 

Please upvote this feature to make this our priority

Regards,
Suriya M.
