### ISSUE TITLE
DocumentEditor: RTL has too many problems

### ISSUE THREAD

**Issue by tyeety** [syncfusion/ej2-angular-ui-components#219]
When using RTL, typing numbers and special characters such as colon and slash, makes editor act crazy!
Spaces place before characters.
Can't insert space before line begins.
Indent not works as it should be
Width of some words changes after pressing space and makes word unshaped.
Undoing and then redo, makes characters sliced.

There are more problems with RTL that I wish them get fixed as soon as possible.

**Comment by Suriya-Murugan** [comment]
Hi tyeety,

We already logged the enhancement task for RTL issues. We will include it in any of our upcoming releases.

Once we have a definite plan for this feature implementation, we will move the feedback to scheduled status with a tentative release timeline. 

You can track the status of the feature through the below feedback link:

https://www.syncfusion.com/feedback/25287/rtl-text-rendering-enhancement


Regards,
Suriya M.
