### ISSUE TITLE
Multiselect Dropdown groupTemplate not working

### ISSUE THREAD

**Issue by ninopetrovic** [syncfusion/ej2-angular-ui-components#22]
**query 1:** How can i achieve that when using CheckBox mode AND grouping in Multiselect-dropdown component.. I would see check-boxes also on group items. So that when I select a grouping item the component will select all of the items in that group. (this was possible in ej1)

**query 2:**  If query 1 cannot be achieved then I would like to use groupTemplate. I tried it and it doesnt seem to work.. 

**example:** 
```
<ejs-multiselect
  #xyzMultiselectDropdown
  [dataSource]='dataSource'
  [fields]='fields'
  [value]="value"
  [mode]='mode'
  [placeholder]='placeholder'
  [popupHeight]="popupHeight"
  [closePopupOnSelect]="false"
  [showSelectAll]="showSelectAll"

  (select)="select($event)"
  (change)="change($event)"
  (blur)="blur($event)"
  (removed)="removed($event)"
  (actionComplete)="actionComplete($event)"
>
  <!--TEMPLATES-->
  <ng-template #groupTemplate="" let-data="">
    <span (click)="myFunction();">{{data.name}}</span>
  </ng-template>

</ejs-multiselect>
```

**Comment by PrinceOliver** [comment]
Hello @ninopetrovic,

Greetings from Syncfusion support.  

We have already considered “support for Multiselect grouping with checkbox” as feature. We have planned this in the roadmap of our 2019 Volume 2 main release, which is expected to be rolled out in the month of June 2019. You can now track the current status of the request, review the proposed resolution timeline, and contact us for any further inquiries through this link: https://www.syncfusion.com/feedback/5301/         

Regards,     
Prince

**Comment by PrinceOliver** [comment]
Hi @ninopetrovic,

Thank you for your patience.

We have included the feature “_Support for Multiselect grouping with checkbox_” in the Volume 2, 2019 beta release (**v17.2.28-beta**). Kindly refer to the following release notes section: https://ej2.syncfusion.com/angular/documentation/release-notes/17.2.28/#multiselect 

Demo link: https://npmci.syncfusion.com/hotfix/17.2.0.1/angular/demos/#/material/multi-select/grouping-with-checkbox 

We suggest you upgrade to the latest version in your end.

Regards,
Prince

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution already provided.
