### ISSUE TITLE
problem get index datasource ej2-angular-list

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#225]
how to get index item customize template in ej2-angular-list

**Comment by Indhumathy-Loganathan** [comment]
Hi Messxay,

You can retrieve the index values of the ListView datasource by using the [DataManager](https://ej2.syncfusion.com/javascript/documentation/data/getting-started/) component [Query](https://ej2.syncfusion.com/javascript/documentation/api/data/query/) class. For your reference, we have retried all the id values of ListView items with a button click. Check the below code snippet.

`click() {
  let list = new DataManager(this.data).executeLocal(
    new Query().select(['id'])
  );
  console.log(list);
}
`

You can find the sample from below link.

https://stackblitz.com/edit/angular-ybgrxj?file=app.component.ts

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for one week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
