### ISSUE TITLE
add customize event in day ejs-calendar

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#226]
How to add custom event in day ejs-calendar after render finished calendar,
![image](https://user-images.githubusercontent.com/29179069/166909581-6171c332-0cb3-4f80-98f2-33d6f9f10f71.png)
 i'm follow document, but is not usefully, i do not think event renderDayCell usefully.

**Comment by Deepak-Ramakrisnan** [comment]
Hi Messexay,


We can specify the day cell with customized class name and make difference in the UI by using renderDayCell event .  You can refer the below demo link for detailed explanation.



Demo Link : https://ej2.syncfusion.com/angular/demos/#/bootstrap5/calendar/special-dates



Let us know if you needs to dynamically update the special dates (irrespective to the renderDayCell  event) along with use case details, to proceed further in our end.


Thanks,

Deepak R.

**Comment by messxay** [comment]
> 

Hi Deepak-Ramakrisnan,
event renderDayCell usefully when i load event at the same time calendar, but i custom event when calendar loaded finish, it not help.
