### ISSUE TITLE
control multiselect load data type tree

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#227]
how to load control multiselect type dropdown tree. I 'm tried insert treeview in template but it not effective.

**Comment by PrinceOliver** [comment]
Hi @messxay 

We have a DropDownTree component in our library, which will meet your requirement. Please check the demo links below

https://ej2.syncfusion.com/angular/demos/#/material/drop-down-tree/checkbox 
https://ej2.syncfusion.com/angular/demos/#/material/drop-down-tree/multiple-selection 

Let us know if you need any further information.

Regards,
Prince

**Comment by messxay** [comment]
I want to custom filler as image
![image](https://user-images.githubusercontent.com/29179069/167815640-dfa2f34b-0c23-462e-8d70-054a8dd224f2.png)
 filter not inside dropdown. what to do???

**Comment by Indhumathy-Loganathan** [comment]
Hi @messxay,

We have placed search box inside the Dropdown Tree popup. This is the default behavior. Check the below link.

https://ej2.syncfusion.com/angular/demos/#/material/drop-down-tree/filtering

If you wants to perform filtering within the initial input box, kindly check whether the **AutoComplete** or **MultiSelect Dropdown** suitable for you. Check the below references.

https://ej2.syncfusion.com/angular/demos/#/material/auto-complete/grouping-icon

https://ej2.syncfusion.com/angular/demos/#/material/multi-select/filtering

Please check the shared details and get back to us if you need any further assistance.

Regards,
Indhumathy L

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
