### ISSUE TITLE
set template after event open multiselect

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#228]
How to set template after event open of multiselect

**Comment by PrinceOliver** [comment]
Hi @messxay 

You can use the open event in the multiselect component and set the itemTemplate / valueTemplate property to dynamically set the required template.

[HTML]
`<ejs-multiselect id='multiselect' [dataSource]='data' [fields]='fields' (open)='onOpen($event)' [itemTemplate]="itemTemplate" [valueTemplate]="valuetemplate"
[placeholder]='watermarks'></ejs-multiselect>
`

[TS]
`
public onOpen = (e) => {
    this.valuetemplate = '<div class="name"> ${Name} - ${Code} </div></div>';
    this.itemTemplate =  '<div style="width:100%;height:100%;">'
            + '<div class="name"> ${Name} - ${Code} </div></div>'
};`


Sample: https://stackblitz.com/edit/angular-hvifx2

Regards,
Prince

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
