### ISSUE TITLE
Couldn't make rounded corner on stacking column chart when value is zero

### ISSUE THREAD

**Issue by hasan-enosis** [syncfusion/ej2-angular-ui-components#229]
I am trying to make the **last** corner rounded in a stacking column chart. I am passing the corner radius configuration in the HTML template. The configuration is working fine but it couldn't round the last column when the value is **zero** as shown in the image. How do I fix the last column when the value is **zero**? I have added a demo link for your convenience. Actually, I need to make the previous column rounded when the last column value is zero. 

**Demo:** : [Stacking Column Chart](https://stackblitz.com/edit/angular-hgyysz?file=app.component.ts,app.component.html)

![image](https://user-images.githubusercontent.com/58516749/168574778-2c612d63-9375-48d7-a9ad-425a408a21f2.png)

**Comment by G-Durga** [comment]
Hi Hasan,

Your requirement can be achieved using pointRender event. Please check with below snippet and sample.

      pointRender:(args: IPointRenderEventArgs)=>{
           if(args.series.index == 2 && args.point.index == 0)
                args.series.cornerRadius = {topLeft: 10, topRight:10};
           else if(args.series.index == 2)
               args.series.cornerRadius = {topLeft: 0, topRight:0};
        }
      
![image](https://user-images.githubusercontent.com/93256798/169329650-cc9e1e29-3bd7-49bd-8334-6d47ea347e30.png)


Sample : [https://stackblitz.com/edit/fzvtyz-vcklnj?file=index.ts](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Ffzvtyz-vcklnj%3Ffile%3Dindex.ts&data=05%7C01%7Cdurga.gopalakrishnan%40syncfusion.com%7C715fb17699f140517c1208da399212de%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637885596779734951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FJRJscJ7cQWWX9hW2bgNBJmUeNP91Vq41JMYtWQ%2B1YM%3D&reserved=0)


Please let us know if you have any concerns.

Regards,
Durga Gopalakrishnan.

**Comment by hasan-enosis** [comment]
Hi Durga, 

Thank you for your response. You have handled the problem statically. I need a dynamic solution where I can round the top series/column corner. Please click on a legend (France or France + Italy)  and you will see the corner doesn't round as expected.
There are a lot of cases here. You can try some other combinations also.
 
![image](https://user-images.githubusercontent.com/58516749/169386062-1c7668cd-a5c6-4bf9-a739-7f2cee226bcd.png)

**Comment by G-Durga** [comment]
Hi Hasan,

Currently, we don’t have support to apply corner radius for any particular point in a series. Corner radius will be applied for all the points in the series. You can apply corner radius for required point using pointRender event as mentioned earlier by checking the pointIndex and seriesIndex. 

Then, while clicking the particular legend item, you can obtain the required series in legendClick event and change the condition based on that. Please check with below API reference links.

API :
[https://ej2.syncfusion.com/documentation/api/chart/#legendclick](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fej2.syncfusion.com%2Fdocumentation%2Fapi%2Fchart%2F%23legendclick&data=05%7C01%7Cdurga.gopalakrishnan%40syncfusion.com%7C7054949b8f7f4bc9293308da3e341db8%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637890690818778762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Al%2BFaKA8BCJfxETGOIc%2BqKQ06XISzPLJn50%2FABNgd5E%3D&reserved=0)
[https://ej2.syncfusion.com/documentation/api/chart/#pointrender](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fej2.syncfusion.com%2Fdocumentation%2Fapi%2Fchart%2F%23pointrender&data=05%7C01%7Cdurga.gopalakrishnan%40syncfusion.com%7C7054949b8f7f4bc9293308da3e341db8%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637890690818778762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pfyn4of88elBoPlYVLCeCF9avGrMiIYN4BbT5Dvs%2Bxg%3D&reserved=0)

Please revert us if you have any concerns.

Regards,
Durga Gopalakrishnan.

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for one week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
