### ISSUE TITLE
bind data Hierarchical in diagram

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#230]
how to bind data type Hierarchical in diagram,
 ex: data = [
{
id : "number1", 
text: "number one",
childrend: [
{id: "number11",
 text: "number one one", 
parent: "number1"
},{id: "number12",
 text: "number one two", 
parent: "number1"
},]},]

**Comment by shyamg1991** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ShyamG/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/ShyamG/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ShyamG/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p style='margin:0in;background:white'><span style='color:black;mso-color-alt:
windowtext'>Hi messxay,</span><o:p></o:p></p>

<p style='margin-top:0in;margin-right:0in;margin-bottom:7.5pt;margin-left:0in;
background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
word-spacing:0px'><span style='font-size:10.5pt;font-family:Heebo'><o:p>&nbsp;</o:p></span></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='color:black;
mso-color-alt:windowtext'>We have created a sample to bind data for
hierarchical tree. We have modified the given data and bind that data to the
hierarchical layout. By using the diagram dataSource property we can able to
map the id and parentId for the data. In the diagram dataSource map the proper
Id and parentId from the data. The ID property is used to define the unique
field of each JSON data. The parentId property is used to define the parent
field which builds the relationship between ID and the parent field.<span
style='box-sizing: border-box'>&nbsp;&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='box-sizing: border-box'><span
style='color:black;mso-color-alt:windowtext'>&nbsp;</span></span><o:p></o:p></p>



// The JSON should be in the below format (array of   objects. No need to nest multiple array objects)   public Data: any = [       {         id:   'number1',         text:   'number one',       },       {   id: 'number11', text: 'number one one', parent: 'number1' },       {   id: 'number12', text: 'number one two', parent: 'number1' },     ];         public data:   Object = {       //sets the fields to   bind       id:   'id',       parentId:   'parent',       dataSource: new   DataManager(this.Data),       //binds the data with   the nodes       doBinding:   (nodeModel: NodeModel, data: object, diagram: Diagram) => {         nodeModel.annotations   = [{ content: (data as any).text }];       },     };
--




<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='box-sizing: border-box'><span
style='color:black;mso-color-alt:windowtext'>&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='box-sizing: border-box'><span
style='color:black;mso-color-alt:windowtext'>&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='color:black;
mso-color-alt:windowtext'>By using the diagram’s doBinding we can able to
populated the diagram with the nodes and connectors based on the information
provided from an external data source Set the data for the organizational chart
, and bind that data through diagram’s doBinding feature. Similarly,<br
style='box-sizing: border-box'>
you can able to bind the data in doBinding feature in your sample and create
layout.<span style='box-sizing: border-box'>&nbsp;&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='box-sizing: border-box'><span
style='color:black;mso-color-alt:windowtext'>&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='color:black;
mso-color-alt:windowtext'>We have attached a sample for your reference. Please
find the sample in below link<span style='box-sizing: border-box'>&nbsp;&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='box-sizing: border-box'><span
style='color:black;mso-color-alt:windowtext'>&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='color:black;
mso-color-alt:windowtext'>Sample:&nbsp;<a
href="https://stackblitz.com/edit/angular-napjqg?file=app.component.ts"
style='box-sizing: border-box;user-select: auto'><span style='color:#2E2EF1'>https://stackblitz.com/edit/angular-napjqg?file=app.component.ts</span></a></span><o:p></o:p></p>

<p style='margin-top:0in;margin-right:0in;margin-bottom:7.5pt;margin-left:0in;
background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
word-spacing:0px'><span style='font-size:10.5pt;font-family:Heebo'><o:p>&nbsp;</o:p></span></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='color:black;
mso-color-alt:windowtext'>For more information about databinding, please refer
to the below UG Link</span><o:p></o:p></p>

<p style='margin-top:0in;margin-right:0in;margin-bottom:7.5pt;margin-left:0in;
background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
word-spacing:0px'><span style='font-size:10.5pt;font-family:Heebo'><o:p>&nbsp;</o:p></span></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='color:black;
mso-color-alt:windowtext'>UG Link:&nbsp;<a
href="https://ej2.syncfusion.com/angular/documentation/diagram/data-binding/"
style='box-sizing: border-box;user-select: auto'><span style='color:#2E2EF1'>https://ej2.syncfusion.com/angular/documentation/diagram/data-binding/</span></a></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='box-sizing: border-box'><span
style='color:black;mso-color-alt:windowtext'>&nbsp;</span></span><o:p></o:p></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><b style='box-sizing: border-box'><span
style='color:black;mso-color-alt:windowtext'>Note</span></b><span
style='color:black;mso-color-alt:windowtext'>: The layout gets arranged if the
data contains a parent-child relationship. If it does not have any parent-child
relationship means then layout does not arranged.<span style='box-sizing: border-box'>&nbsp;&nbsp;</span></span><o:p></o:p></p>

<p style='margin-top:0in;margin-right:0in;margin-bottom:7.5pt;margin-left:0in;
background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
word-spacing:0px'><span style='font-size:10.5pt;font-family:Heebo'><o:p>&nbsp;</o:p></span></p>

<p style='margin:0in;background:white;box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='color:black;
mso-color-alt:windowtext'>Regards</span><o:p></o:p></p>

<p class=MsoNormal style='box-sizing: border-box;color:rgba(0, 0, 0, 0.87);
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial;word-spacing:0px'><span style='mso-bidi-font-family:
Calibri;mso-bidi-theme-font:minor-latin'>Shyam G<o:p></o:p></span></p>


</body>

</html>

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 4 days. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
