### ISSUE TITLE
clear all chip selection multiselect

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#231]
Hi ad, I want clear all or clear one more item in chip selection of control multiselect, i updated value of it, but it not draw value chip. below image.
![image](https://user-images.githubusercontent.com/29179069/175461394-ead83270-691c-4973-9052-b4dd47debeff.png)
**value selected**
![image](https://user-images.githubusercontent.com/29179069/175461429-736a6919-9fa0-49cf-a8c2-1b6e23251bca.png)
**value chip draw**
thanks.

**Comment by PrinceOliver** [comment]
Hi @messxay,

We can clear the selection in the multiselect through the following properties and methods

•	We can use the value property to clear one or more selections.
https://ej2.syncfusion.com/angular/documentation/api/multi-select#value

•	We can use the clear method to clear the selected values.
https://ej2.syncfusion.com/angular/documentation/api/multi-select#clear

•	We can use the selectAll method and pass a Boolean value to select or deselect all items.
https://ej2.syncfusion.com/angular/documentation/api/multi-select#selectall

Kindly check the above suggestions and let us know if this meets your requirements.

Regards,
Prince

**Comment by PrinceOliver** [comment]
Hi @,

We can clear the selection in the multiselect through the following properties and methods

•	We can use the value property to clear one or more selections.
https://ej2.syncfusion.com/angular/documentation/api/multi-select#value

•	We can use the clear method to clear the selected values.
https://ej2.syncfusion.com/angular/documentation/api/multi-select#clear

•	We can use the selectAll method and pass a Boolean value to select or deselect all items.
https://ej2.syncfusion.com/angular/documentation/api/multi-select#selectall

Kindly check the above suggestions and let us know if this meets your requirements.

Regards,
Prince

**Comment by syncsiva** [comment]
@messxay This issue has been resolved and has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
