### ISSUE TITLE
`ej2-angular-base` v20.2.36 peerDependencies

### ISSUE THREAD

**Issue by Phillip9587** [syncfusion/ej2-angular-ui-components#235]
The package defines the peer dependencies:
```json
 "peerDependencies": {
    "@angular/common": "4.10.0 - 11.1.1",
    "@angular/compiler": "4.10.0 - 11.1.1",
    "@angular/core": "4.10.0 - 11.1.1",
    "@angular/forms": "4.10.0 - 11.1.1",
    "@angular/platform-browser": "4.10.0 - 11.1.1",
    "@angular/platform-browser-dynamic": "4.10.0 - 11.1.1"
  }
```

But the Release Notes say that from this version on Angular 12+ is supported: 
> From this release, Syncfusion provided the Ivy-compatible support for the Angular packages. Ivy Angular packages support Angular versions 12 and above. While using the latest Angular packages in the Angular 11 and below version application, components will not work. To provide the latest features and fixes for Angular versions 11 and below, Syncfusion will maintain the Angular packages tagged with ngcc. To install Angular packages that are compatible with ngcc for the Angular versions 11 and below application, run the npm install @syncfusion/ej2-angular-grids@ngcc command.

Please fix this!

**Comment by Mydeensn** [comment]
Hi @Phillip9587 ,

Thanks for contacting syncfusion support.

Our components are compatible upto the angular 14 version. We have resolved the peer dependency issue in our side, please update the packages to the latest version to include the changes.

Regards,
Mydeen S N
