### ISSUE TITLE
Impossible to type [space] in textbox with inline editing in grid.

### ISSUE THREAD

**Issue by foe-dnm** [syncfusion/ej2-angular-ui-components#237]
Impossible to type [space] in textbox with inline editing in grid.

Example:
https://ej2.syncfusion.com/angular/demos/#/material/grid/normal-edit

try to enter a [space] in the Customer ID column.

**Comment by rajapandiyan-settu** [comment]
Hi,

Thanks for contacting Syncfusion support.

We have confirmed that the reported behavior is a breaking issue from our side and already logged this as - “Not able to type whitespaces in inline edit text fields on Mac”. Thank you for taking the time to report this issue and helping us improve our product. At Syncfusion, we are committed to fixing all validated defects (subject to technical feasibility and [Product Development Life Cycle](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fsupport%2Fproduct-lifecycle%2Festudio&data=05%7C01%7Crajapandiyan.settu%40syncfusion.com%7Ce609c74b2a264e52b17e08da7f530920%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637962291864663261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Eq3L7Bm8T927Ghg3CXOoQYw%2BpgcpPwkj5Xv0A3DRTh0%3D&reserved=0) ) and will include the defect fix in our upcoming patch release which is expected to be rolled out on Aug 17th, 2022.

Regards, 
Rajapandiyan S

**Comment by rajapandiyan-settu** [comment]
Hi,



We are glad to announce that our Essential Javascript2 patch release ([v20.2.44](https://www.npmjs.com/package/@syncfusion/ej2/v/20.2.44)) has been rolled out successfully and in that release we have added the fix of “Not able to type whitespaces in inline edit text fields on Mac” issue. So, please update your Syncfusion packages to the current version and use latest style script to get this.

Release Notes: https://ej2.syncfusion.com/angular/documentation/release-notes/20.2.44/?type=all#grid

Find the below sample for your reference.

Sample: https://stackblitz.com/edit/angular-fohpod?file=app.component.html


Regards,
Rajapandiyan S

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
