### ISSUE TITLE
set width or heigth with ej2 Tab

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#238]
I want set width for tab header of me with properties headerPlacement="Left"
![image](https://user-images.githubusercontent.com/29179069/179462486-f39a9f69-3070-4dff-bc51-ef1fdbba66a0.png)
or heigth with  headerPlacement default.
![image](https://user-images.githubusercontent.com/29179069/179462744-584dea48-d125-4d93-b447-d4a0768be2ff.png)
present i using CSS set for them, but i don't contentment, there is a solution orther???? Thanks.

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
