### ISSUE TITLE
NG-Rich Text Editor_Text editing issues

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#239]
Dear Team, 
Kindly watch attached video for the weird behavior of Editor.
when we try to use back space to bring bottom line to top line it is taking top line word to its top line.
I have attached word source document for your observation.

please copy past the word content inside angular Rich text editor and check the video for the issues.
Note: This issues not happing in React Rich Text Editor while copay paste from word

[Synfusion Editor content editing issues.docx](https://github.com/syncfusion/ej2-angular-ui-components/files/9137752/Synfusion.Editor.content.editing.issues.docx)

https://user-images.githubusercontent.com/63642104/179671334-b7e6cf66-c8ea-4950-85bb-52834d2f0cb7.mp4

**Comment by arunjoshtech** [comment]
Dear Vinitha,
The issue I have recorded from your demo website itself.
Kindly use angular Rich text editor demo.  refer below url for demo
https://ej2.syncfusion.com/angular/demos/#/material/rich-text-editor/tools

**Comment by arunjoshtech** [comment]
The issues are found fixed in Your demo server but it was exist in main server when create the issues. I have that video clip attached here. this behavior might be fixed within these days.

https://user-images.githubusercontent.com/63642104/180249146-ff2f287c-692d-40c3-876c-d55883e08b97.mp4

.

**Comment by arunjoshtech** [comment]
Dear Team,
The issues i face again today.
I tested in live angular demo also it is existing.
But in React it is perfectly fine.
Please refer both image for comparison and attached word file for your reproduction of the issues in angular Rich text editor.
[Rich text editor deformation.docx](https://github.com/syncfusion/ej2-angular-ui-components/files/9364359/Rich.text.editor.deformation.docx)
.

![Angular rich text editor](https://user-images.githubusercontent.com/63642104/185181930-2ea7e830-12db-431a-805c-2569f70ac7d0.png)
![react rich text copy past](https://user-images.githubusercontent.com/63642104/185181960-7756a0b7-e8dd-46cf-9883-9136e5cb179b.png)

**Comment by VinithaJeyakumar** [comment]
Hi Arun,


We have included the fix for the issue "**Copy/Pasting contents from Word to Editor, doesn't give proper formatting and causing improper formats when try to backspace the element in RTE**" with our patch release version **20.3.60**. So please upgrade your package to the latest to resolve the reported issued from your end.

**Release notes**: 
https://ej2.syncfusion.com/documentation/release-notes/20.3.60/?type=all#richtexteditor

Regards,
Vinitha

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
