### ISSUE TITLE
Issues with Jest and mjs files

### ISSUE THREAD

**Issue by FacePalmDev** [syncfusion/ej2-angular-ui-components#241]
Hello, 

I'm trying to use Syncfusion in our Nx Angular application which uses jest for testing. However because sync fusion grid seems to be using mjs files the tests are failing with:
```
SyntaxError: Cannot use import statement outside a module
```
My current jest config contains the following but it just doesn't work:
``` javascript
 moduleFileExtensions: ["ts", "js", "mjs"],
  transform: {
    '^.+\\.(ts|js|mjs|html)$': 'jest-preset-angular'
  },
  transformIgnorePatterns: [
    'node_modules/(?!.*.mjs$|@ckeditor)'
  ],
```
Can someone please help?

**Comment by rajapandiyan-settu** [comment]
Hi,

Thanks for contacting Syncfusion support.

**Query: SyntaxError: Cannot use import statement outside a module**

The reported query is a common issue and it is not related to Syncfusion components. Kindly refer to the following public links to resolve this problem.

[https://stackoverflow.com/questions/58613492/how-to-resolve-cannot-use-import-statement-outside-a-module-in-jest](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F58613492%2Fhow-to-resolve-cannot-use-import-statement-outside-a-module-in-jest&data=05%7C01%7Crajapandiyan.settu%40syncfusion.com%7C7014bfb699994b99c95e08da89c6e3cb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637973784572808369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WF6GKZ4XJKQu9t6Sv0Xk7YaqvN4DqSD3ggwTeYm3Tz8%3D&reserved=0)
[https://stackoverflow.com/questions/61781271/jest-wont-transform-the-module-syntaxerror-cannot-use-import-statement-outsi](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F61781271%2Fjest-wont-transform-the-module-syntaxerror-cannot-use-import-statement-outsi&data=05%7C01%7Crajapandiyan.settu%40syncfusion.com%7C7014bfb699994b99c95e08da89c6e3cb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637973784572808369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A05YePyEpoWRn%2BW7lwPkwPRxUxWJ4f7c3aC1sB%2B%2Bo9I%3D&reserved=0)
[https://stackoverflow.com/questions/59709939/jest-cannot-use-import-statement-outside-a-module](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F59709939%2Fjest-cannot-use-import-statement-outside-a-module&data=05%7C01%7Crajapandiyan.settu%40syncfusion.com%7C7014bfb699994b99c95e08da89c6e3cb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637973784572808369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LctvzbFaHIZ2iIEERUOBM%2F4l%2BAhv396x%2Bn5DpYQJ9gU%3D&reserved=0)
[https://stackoverflow.com/questions/66483940/syntaxerror-cannot-use-import-statement-outside-a-module-error-while-testing](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F66483940%2Fsyntaxerror-cannot-use-import-statement-outside-a-module-error-while-testing&data=05%7C01%7Crajapandiyan.settu%40syncfusion.com%7C7014bfb699994b99c95e08da89c6e3cb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637973784572808369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lLaSGFiBJzPcXedIEZpzElOHAKQwtlB9Sv8xe3jDP0U%3D&reserved=0)
[https://stackoverflow.com/questions/59879689/jest-syntaxerror-cannot-use-import-statement-outside-a-module](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F59879689%2Fjest-syntaxerror-cannot-use-import-statement-outside-a-module&data=05%7C01%7Crajapandiyan.settu%40syncfusion.com%7C7014bfb699994b99c95e08da89c6e3cb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637973784572808369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wqxG0XMp80C95sfgdpZyxpYhTcielxl2f7fzIHQDRpI%3D&reserved=0)
[https://www.querythreads.com/how-to-resolve-cannot-use-import-statement-outside-a-module-in-jest/](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.querythreads.com%2Fhow-to-resolve-cannot-use-import-statement-outside-a-module-in-jest%2F&data=05%7C01%7Crajapandiyan.settu%40syncfusion.com%7C7014bfb699994b99c95e08da89c6e3cb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637973784572964585%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3SYX1sjdSfnQHVOZV1RjVr1uEcvDlO15OgndV6Qg%2FnU%3D&reserved=0)

Regards, 
Rajapandiyan S

**Comment by syncsiva** [comment]
This issue has been closed due to no response from the original author. Please feel free to reopen, if you have more information that can help us investigate the issue further.
