### ISSUE TITLE
Pivot Table missed row drill-down option

### ISSUE THREAD

**Issue by nm-a** [syncfusion/ej2-angular-ui-components#242]
Hi Team,
Not able to see row drill-down option in https://stackblitz.com demos.

**Stackblitz:**
<img width="428" alt="image" src="https://user-images.githubusercontent.com/7089157/183270935-bf152d95-583e-48ce-990c-9099e94ce24b.png">

**Syncfusion:**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/7089157/183270908-b4d5f9ed-b8af-498d-a4f9-f77339bd2f36.png">

Thank you

**Comment by AngelinFaithSheeba** [comment]
Hi Team,



This is a known issue that has been resolved and included in our Essential Studio 2022 Volume 2 SP Release V20.2.43. Please refer to the following sample and screenshot.



Sample: [https://stackblitz.com/edit/angular-qrekh8-2qmlny?file=app.component.html](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Fangular-qrekh8-2qmlny%3Ffile%3Dapp.component.html&data=05%7C01%7Cangelinfaithsheeba.p%40syncfusion.com%7C529cb3fac915468060b208da79406062%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637955614646437781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PTIHZKz7mrLfW%2FddgVl%2BEt6R325zFuivQ8DKdeUwE9E%3D&reserved=0)



Screnshot:


![rte_image_98](https://user-images.githubusercontent.com/93255570/183618519-090c58f0-2b8a-4c17-97eb-32d118216d5e.png)

  

Please let us know if you have any concerns.



Regards,

Angelin Faith Sheeba

**Comment by syncsiva** [comment]
This issue has been resolved. Please feel free to reopen if you have any further queries.
