### ISSUE TITLE
pdf animation not working

### ISSUE THREAD

**Issue by messxay** [syncfusion/ej2-angular-ui-components#243]
I using ejs-pdfViewer inside ejs-dialog properties injectedModules length 0, when i put it outside ejs-dialog then it works.
![image](https://user-images.githubusercontent.com/29179069/184129219-45e8dd89-49f4-47b7-86c4-e431c9d67b96.png)
down here code of me.
_<ejs-pdfviewer
          #pdfviewer
          id="pdfViewer"
          [(serviceUrl)]="service"
          [enableToolbar]="false"
          [enableNavigationToolbar]="false"
          [enableAnnotationToolbar]="false"
          [enableThumbnail]="true"
          (created)="onCreated($event)"
          (documentUnload)="changeCanActState(true)"
          (annotationAdd)="addAnnoEvent($event)"
          (annotationMove)="resetTime($event)"
          (annotationRemove)="removeAnnot($event)"
          (annotationResize)="resetTime($event)"
          (annotationSelect)="selectedAnnotation($event)"
          (annotationPropertiesChange)="resetTime($event)"
          (printEnd)="cancelPrint($event)"
          (documentLoad)="loadingAnnot($event)"
          (pageChange)="pageChange($event)"
          [zoomValue]="zoomValue"
          (zoomChange)="changeZoomValue($event)"
          [ajaxRequestSettings]="ajaxSetting"
          style="
            height: 100% !important;
            width: 100% !important;
            position: relative;
            display: block;
          "
        >
        </ejs-pdfviewer>_

**Comment by syncsiva** [comment]
This issue has not had any activity for one week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
