### ISSUE TITLE
Resizing event on table

### ISSUE THREAD

**Issue by cesvelasquez22** [syncfusion/ej2-angular-ui-components#245]
Do you have any support such as an event that triggers when resize a whole table?

I mean with the behavior here:
![image](https://user-images.githubusercontent.com/51433362/191118213-817aeb88-c09c-4a0e-8858-1510fa2fb918.png)

Something like events on resizing images:
![image](https://user-images.githubusercontent.com/51433362/191118469-586a9829-21b7-441f-8000-e1ed1a0636c8.png)

**Comment by VinithaJeyakumar** [comment]
<html>
<body>
<div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">Hi,</span></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">Yes, we have events which will trigger while resizing the table, please check the events below,</span></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);">

Event | Action
-- | --
resizeStart | Trigger while starting the resize in table
resizing | Triggers while resizing the table
resizeStop | Triggers when we stop resizing the table

<br></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><b>API Link</b></span><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><span> </span>: </span><a href="https://ej2.syncfusion.com/angular/documentation/api/rich-text-editor/#resizestart" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline;"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">https://ej2.syncfusion.com/angular/documentation/api/rich-text-editor/#resizestart</span></a><br></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><b>Sample</b></span><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">: </span><a href="https://stackblitz.com/edit/angular-2evkhn?file=app.component.ts,app.component.html" id="LPlnkOWALinkPreview" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline;"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">https://stackblitz.com/edit/angular-2evkhn?file=app.component.ts,app.component.html</span></a></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">Regards,</span></div><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 11pt; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Helvetica Neue&quot;, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">Vinitha</span></div><br><div class="elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br style="color: rgb(0, 0, 0); font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>

**Comment by cesvelasquez22** [comment]
Thanks
