### ISSUE TITLE
Need to show two consecutive months in date-range picker

### ISSUE THREAD

**Issue by anoop-kiwi** [syncfusion/ej2-angular-ui-components#25]
Hello Team,

I want to show two consecutive months in the date-range picker. Please let me know how I can achieve this. I also attached my requirement.

Thanks in Advance.

![img1](https://user-images.githubusercontent.com/47739003/57768303-fab3df00-7728-11e9-9376-ea6279404c99.png)

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

Greetings from Syncfusion.

Currently we have not provided the support to **display two consecutive months in DateRnagePicker.** We have considered the reported requirement as a feature at our end and this support will be included in any one of our upcoming releases. We appreciate your patience until then. Please track the details of this feature from the below feedback link.

**Feedback Link**: https://www.syncfusion.com/feedback/6588/provide-the-support-for-two-consecutive-
months-in-daterangepicker

Regards,
Berly B.C
