### ISSUE TITLE
Leak in @syncfusion/ej2-angular-richtexteditor

### ISSUE THREAD

**Issue by kievsash** [syncfusion/ej2-angular-ui-components#255]
Hi

I observe detached Elements leak in @syncfusion/ej2-angular-richtexteditor ^21.1.35
![](https://github.com/kievsash/syncfusion-richtextedit-leak/raw/main/syncfusion_richedit_leak.gif)

I created minimal Angular repo with reproduce code:  [https://github.com/kievsash/syncfusion-richtextedit-leak](https://github.com/kievsash/syncfusion-richtextedit-leak)

Steps to reproduce:
1. ng serve and go to localhost:4200
2. go back and forth to test page
3. With Edge Detached Elements DevTools tab (or ChromeDevTools Performance monitor) observe that Detached elements number is increasing

Please take a look

**Comment by kievsash** [comment]
I observed similar issue in ejs-checkbox as well

**Comment by kievsash** [comment]
To reproduce issue you should
1. git clone my repo
2. cd <repoFolder>
3. npm i
4. ng serve
5. go to page with rich-text editor and back(but back not browser button but routerLink to root page)

What was thr issue you couldnt start reproduce app?

**Comment by kievsash** [comment]
I downloaded your reproduce app and could reproduce there increase in DOM notes on each entering to page with rich-editor

**Comment by kievsash** [comment]
And here is reproduce in your app in Edge Dev tools - > detached Elements tab
![syncfusion_richedit_leak2Edge](https://user-images.githubusercontent.com/15340874/233479366-8d6e7a6c-7f35-4f03-b018-9edbff1263e8.gif)

**Comment by VinithaJeyakumar** [comment]
Hi kievsash,


We have moved the feedback status to public. Now you can access the bug feedback. Please check the link below,

https://www.syncfusion.com/feedback/42986/need-to-resolve-detached-element-leak-in-angular-platfrom

Regards,
Vinitha

**Comment by gsumankumar** [comment]
For housekeeping purposes, we are closing this ticket. You can track the progress of the reported bug by clicking on the feedback link below.
https://www.syncfusion.com/feedback/42986/need-to-resolve-detached-element-leak-in-angular-platfrom

**Comment by kievsash** [comment]
@gsumankumar , one remark

In Form-base.ts you addEventListener on AfterViewInit method
![image](https://github.com/user-attachments/assets/bf88f7d8-fb97-4228-9300-28d7b9da8ea5)

But AFAI see you do not remove these listeners in component which uses FormBase
![image](https://github.com/user-attachments/assets/c97e6788-d1e8-4328-b633-4ba34e65b63a)

Maybe it make sense to add ngOnDestroy to FormBase where you removeEventListeners
and then call it from ngOnDestroy of specific component which uses FormBase()? (similar to what you do with  this.formContext.ngAfterViewInit(this); but with ngOnDestroy also)
