### ISSUE TITLE
NavigationPane not showing folder tree in FileManager

### ISSUE THREAD

**Issue by davidluanmta** [syncfusion/ej2-angular-ui-components#257]
NavigationPane not showing folder tree
![Screenshot_1](https://github.com/syncfusion/ej2-angular-ui-components/assets/46497044/de064d73-ff13-4956-ad06-735fdd8ceafb)

**Comment by davidluanmta** [comment]
It may be error in version 21.2.4. I has changed to 17.2.47 then it work ok

**Comment by Indhumathy-Loganathan** [comment]
Hi David, The reported issue with **“Files and folders are disappear in File Manager navigation pane”** have been resolved in our latest release **(V21.2.5)**. To access this fix, we suggest you update the package to **21.2.5** version and we include the sample in the latest version for your reference.

**Sample :**  https://stackblitz.com/edit/fyjlby?file=index.html
