### ISSUE TITLE
Missing License Files

### ISSUE THREAD

**Issue by wcroteau** [syncfusion/ej2-angular-ui-components#258]
While a license file exists in your source repo it seems that the license was never configured to be included in several of your npm packages.

For example see the "Code" view on npmjs.com for ej2-angular-buttons - there's no license file:
https://www.npmjs.com/package/@syncfusion/ej2-angular-buttons?activeTab=code

I note however that there IS a license for ej2-angular-base:
https://www.npmjs.com/package/@syncfusion/ej2-angular-base?activeTab=code

I have encountered this missing file for the following (not exhaustive list):
ej2-angular-buttons
ej2-angular-inputs
ej2-angular-layouts
ej2-angular-popups
ej2-angular-richtexteditor
ej2-icons
ej2-pdf-exports

Please can you update your build/deploy process so that the file is included as a top-level file in ALL packages?

This makes it impossible for the consumers of your package to adequately include license notices when using build automation tools.

Thanks!

**Comment by TheveshwarJayakumar** [comment]
Hi wcroteau,

Thanks for bringing this to our attention. We have taken this scenario into account and have planned to include the license file for our component package in our upcoming 2023 Volume 2 release, which is scheduled to be rolled out at the end of June.

Regards,
Theveshwar

**Comment by wcroteau** [comment]
That's great, thanks!

**Comment by TheveshwarJayakumar** [comment]
Hi wcroteau,

Thanks for your patience. 

We are glad to announce that our Essential Studio 2023 Volume 2 release has been rolled out, and in this release, we have included the license file with all our component packages. For your reference we have attached the button component package below.

Link: [@syncfusion/ej2-angular-buttons - npm (npmjs.com)](https://www.npmjs.com/package/@syncfusion/ej2-angular-buttons?activeTab=code)

If you require any further assistance or have additional questions, please feel free to let us know. 

Regards,
Theveshwar

**Comment by gsumankumar** [comment]
This issue has been resolved. Please feel free to reopen if you have any further queries.
