### ISSUE TITLE
Feature Request: popupClass property

### ISSUE THREAD

**Issue by sharathdaniel** [syncfusion/ej2-angular-ui-components#267]
Currently we have popupWidth and popupHeight properties for the popup, please add an attribute like popupClass so that it is easier to make different popup styles. I see no other way to do this right now as the popup have a common class.

**Comment by MalleshRavichandran** [comment]
Based on the information, if you wish to differentiate the popup classes, you can achieve distinct styles for popups by leveraging the existing "cssClass" property. This property enables you to apply unique CSS classes to the root element of the component, allowing for customization of the appearance.

**API Reference** : https://ej2.syncfusion.com/angular/documentation/api/drop-down-list/#cssclass

**Comment by sharathdaniel** [comment]
@MalleshRavichandran But this class doesn't get applied to the popup list.

**Comment by MalleshRavichandran** [comment]
To assist you more effectively, we would like to mention that when using the cssClass property in the dropdownlist , the custom class will be applied to dependent component. If you intend to style the dropdown popup list specifically, we recommend using the cssClass property in conjunction with the relevant popup classes to target the dropdown popup list. This approach allows you to customize the appearance of individual dropdown popups.

> .e-custom.e-ddl.e-popup {
       border: 3px solid grey;
  }


Sample : [Njrens (forked) - StackBlitz](https://stackblitz.com/edit/angular-jysf4k-s18u2u?file=src%2Fapp.component.html,src%2Fapp.component.ts)

If you have any concerns or questions , please get back to us.
