### ISSUE TITLE
No examples for Datepicker popup options

### ISSUE THREAD

**Issue by sharathdaniel** [syncfusion/ej2-angular-ui-components#268]
If you go to this [documentation](https://ej2.syncfusion.com/angular/documentation/api/datepicker/popupObjectArgs/#appendto), there is no example how to implement those.

For eg: I want to change the popup position to open always to the top, i don't see how to do that.

**Comment by BuvanaSathasivam** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/BUVANA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/BUVANA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/BUVANA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">


</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal>Hi Sarathdaniel,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Thank you for reaching out to Syncfusion support.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>We understand your concern regarding the placement of the
EJ2 DatePicker popup. By default, the popup appears under the input component.
If there's insufficient space to display it there, it will be positioned at the
top of the input element.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>To address your issue, we recommend adjusting the popup
position or offset width in the open event of the DatePicker component. You can
set the popup position X as &quot;left&quot; and Y as &quot;top&quot; in the
open event, or alternatively, you can adjust the offsetX and offsetY positions
with numeric values to suit your specific requirements.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>For your convenience, here's a sample code snippet
illustrating how to implement these changes:<o:p></o:p></p>


`open(args: PopupEventArgs) {
    args.popup.position = { X: "left", Y: "top" }; // changing popup position  
  }
`

OR
` open(args: PopupEventArgs) {
    args.popup.offsetX = 0; // changing the popup position with set any number value
    args.popup.offsetY = -150;
  }
`
<p class=MsoNormal>You can also refer to our sample implementation on
StackBlitz <a
href="https://stackblitz.com/edit/angular-rsitl3-wrxk3a?file=src%2Fapp.component.html,src%2Fapp.component.ts">here</a>
and explore the API documentation <a
href="https://ej2.syncfusion.com/angular/documentation/api/datepicker/#open">here</a>
for further details.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>We'll ensure to include this information in our upcoming
documentation releases.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Regards,<o:p></o:p></p>

<p class=MsoNormal>Buvana S<o:p></o:p></p>


</body>

</html>

**Comment by gsumankumar** [comment]
We have addressed the query and are closing the ticket. If you need any further assistance, please feel free to contact us.
