### ISSUE TITLE
ej2-angular-pivotview with Angular 8

### ISSUE THREAD

**Issue by nm-a** [syncfusion/ej2-angular-ui-components#34]
Hi,
ej2-angular-pivotview functionality has been broken with Angular 8, you can validate the same in your demos as well (stackblitz)

thank you

**Comment by DineshBabuYadav** [comment]
Hi,

We are glad to announce that our Essential Studio 2019 Volume 2 Beta Release version 17.2.0.28 is rolled out with the mentioned issue fix and is available for download under the following link.   
   
https://www.syncfusion.com/forums/145548/essential-studio-2019-volume-2-beta-release-v17-2-0-28-is-available-for-download       
   
Note: This issue fix will be included in our main release as well which is expected to be available by mid of July 2019.   
  
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.  
  
Regards,  
Dinesh Babu Yadav

**Comment by nm-a** [comment]
Thank you @DineshBabuYadav
