### ISSUE TITLE
Event for Cancel and Apply button

### ISSUE THREAD

**Issue by anoopyadav-kiwi** [syncfusion/ej2-angular-ui-components#35]
Hello Team,

Is there any click event for cancel and apply button in date-range picker?

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

Greetings from Syncfusion.

We would like to inform you that, our EJ2 DateRangePicker component does not have a public click event for the "**Apply**" and "**Cancel**" buttons. So, we suggest you to **bind the click event manually** for those buttons in the DateRangePicker **open event** as mentioned in the below code example. 

**[app.component.html]**

```html
<div class="control-section">
        <div id="control_wrapper">
            <ejs-daterangepicker (open)="onOpen($event)"></ejs-daterangepicker>
       </div>
</div>
```

**[app.component.ts]**

```ts
import { Component, ViewEncapsulation, Inject } from '@angular/core';
     @Component({
         selector: 'app-root',
         styleUrls: ['app.component.css'],
         templateUrl: 'app.component.html',
         encapsulation: ViewEncapsulation.None
     })
     export class AppComponent {
         onOpen(args) {
             args.popup.element.querySelector('.e-daterangepicker .e-footer .e-apply').addEventListener('click', function () {
                 alert('Apply button is clicked!!');
             });
             args.popup.element.querySelector('.e-daterangepicker .e-footer .e-cancel').addEventListener('click', function () {
                 alert('Cancel button is clicked!!');
             })
         }
 }
```

Please find the sample from the below link.
**Sample Link**: https://stackblitz.com/edit/angular-kqqc4o-dbafb8?file=app.component.html

Regards,
Berly B.C

**Comment by anoopyadav-kiwi** [comment]
Thanks, Team It works.
