### ISSUE TITLE
Pager Bar position 

### ISSUE THREAD

**Issue by abhishekchauhan21** [syncfusion/ej2-angular-ui-components#36]
Please tell me how to customize the Pager bar position on top in react.

**Comment by VigneshNatarajan27** [comment]
Hi Abhishek, 

Kindly refer to the below sample to render the pager component on top of Grid. 

Sample: https://stackblitz.com/edit/react-qpd3b4 

We have achieved this requirement by changing the position of the pager in [dataBound](https://ej2.syncfusion.com/react/documentation/api/grid/#databound) event of Grid. 

Please get back to us if you have further queries. 

Regards,
Vignesh Natarajan

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 2 days. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
