### ISSUE TITLE
Disable all the Sat and Sun from today in date picker calendar

### ISSUE THREAD

**Issue by anoopyadav-kiwi** [syncfusion/ej2-angular-ui-components#37]
Hello Team,

I need to disable all the Sat and Sun from today onwards. So please help me out for this how I can achieve it?

Note: I'm using date picker in angular 7.

Thanks in advance.

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

Greetings from Syncfusion.


We have disabled all the Saturday and Sunday from today onwards using our **renderDayCell** event as mentioned in the below code example.

[**app.component.html**]

```html
<ejs-datepicker (renderDayCell)="onLoad($event)"></ejs-datepicker>
```

[**app.component.ts**]

```ts
onLoad(args: any) {
        if (args.date.valueOf() >= new Date().setHours(0, 0, 0, 0) && (args.date.getDay() === 0 || args.date.getDay() === 6)) { // check the date which are saturday and sunday from today onwards.
            args.isDisabled = true; // disable the weekend date
        }
    }
```

Please find the sample from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-snwjk8-mzux62?file=app.component.ts 

To know more about DatePicker component customization, please refer the below UG documentation link.

**UG Link**: https://ej2.syncfusion.com/angular/documentation/datepicker/customization/ 

Regards,
Berly B.C

**Comment by anoopyadav-kiwi** [comment]
Thanks, Team It works fine.
