### ISSUE TITLE
date-picker not popup calendar on focus element

### ISSUE THREAD

**Issue by sidjai09** [syncfusion/ej2-angular-ui-components#40]

**Comment by BerlyChristopher** [comment]
Hi Sidjai,

Greetings from Syncfusion support.

While checked the reported query (“date-picker not popup calendar on focus element #40”) and we suspect that you want to open the DatePicker popup on the input focus. So, we have prepared the sample and attached it below.

**Sample Link:** https://stackblitz.com/edit/angular-wlo6iv?file=main.ts 

To know more about our DatePicker component, please refer to the below UG and demo link. 

**UG Link:** https://ej2.syncfusion.com/angular/documentation/datepicker/getting-started/?no-cache=1 

**Demo Link**: https://ej2.syncfusion.com/angular/demos/#/material/datepicker/default 

If the provided sample does not meet your requirement, please revert with the exact requirement that will help us to check and provide the exact solution at our end. 

Regards,
Berly B.C

**Comment by sidjai09** [comment]
Thank you for your help it's working.

Thanks &amp; Regards,
Siddharth Jaiswal | UI Developer
