### ISSUE TITLE
Call renderDayCell on API success

### ISSUE THREAD

**Issue by anoopyadav-kiwi** [syncfusion/ej2-angular-ui-components#44]
Hello Team,

I want to call the method for renderDayCell on API success. Please suggest me how I can achieve it?

<ejs-datepicker (renderDayCell)="onLoad($event)"></ejs-datepicker>

I want to call "onLoad" method on API success so that I can disable any specific date of any specific month in any specific year.

Thanks in advance.

Regards,
Anoop

**Comment by sureshkumar1115** [comment]
Hi Anoopyadav,

Greetings from Syncfusion support.

We can disable the particular date, month and year in the DatePicker popup using renderDayCell event as mentioned in the below code example.

```ts
  onLoad(args){
    if((args.date.getDate() == 15) && (args.date.getFullYear() == 2019) && (args.date.getMonth() == 5)) 
    args.isDisabled = true;
  }
```
Please find the sample from the below link.

Sample Link: https://stackblitz.com/edit/angular-ittqcq?file=main.ts 

Regards,
Sureshkumar P.

**Comment by anoopyadav-kiwi** [comment]
Thanks for your response but my requirement is a little bit different. Here is my requirement:

I want to call this renderDayCell method when My rest API is getting success or can I can call this method after some specified time?

Regards,
Anoop

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

We would like to inform you that, “**renderDayCell**” event of the DatePicker will be called **while opening the DatePicker popup**. So, please let us know how did you call the REST API in your application and how did you assigned the date values which need to be disabled in the DatePicker popup?

Also, if possible, please share the **sample** or **code example** that will help us to check and provide the exact solution at our end. 

Regards,
Berly B.C

**Comment by anoopyadav-kiwi** [comment]
Thanks, Team

It works fine.
