### ISSUE TITLE
ej2-angular-richtexteditor build --prod

### ISSUE THREAD

**Issue by Hansel03** [syncfusion/ej2-angular-ui-components#45]
the component richtexteditor  works in the development environment, but when he built the production this fails

the error is:

`ERROR TypeError: Cannot read property 'editorManager' of undefined`

![image](https://user-images.githubusercontent.com/8334348/62073411-a50eaf00-b20e-11e9-9bc4-a13ba5fa407d.png)

i'm building with `ng build --prod --aot`

the version is

        "@syncfusion/ej2-angular-richtexteditor": "^17.2.36",
        "@agm/core": "1.0.0-beta.5",
        "@angular/animations": "8.0.0",
        "@angular/cdk": "8.0.0",
        "@angular/common": "8.0.0",
        "@angular/compiler": "8.0.0",
        "@angular/core": "8.0.0",
        "@angular/flex-layout": "8.0.0-beta.26",
        "@angular/forms": "8.0.0",
        "@angular/material": "8.0.0",
        "@angular/material-moment-adapter": "8.0.0",
        "@angular/platform-browser": "8.0.0",
        "@angular/platform-browser-dynamic": "8.0.0",
        "@angular/router": "8.0.0",

**Comment by NarayanasamyPanneerselvam** [comment]
Hi @Hansel03 ,

Greetings from Syncfusion.

We have validated your issue. Please find the details in below,

We have tried to reproduce your issue with the given steps in the following way. But we were not able to reproduce your issue at our end. 
- AOT with production build and serve the application 
- RichTextEditor render with routing 
  
Could you please provide the below details that will be helpful for us to provide a better solution as earlier as possible. 
1.       Confirm whether you injected HtmlEditorService into your application 
2.       Share the example code block used in RTE module import and service injected into your application.
3.       Share the stack trace if any script error is thrown. 
4.       Share the video demo of your issue / hosted link of your sample 
 
Regards, 
Narayanasamy P.

**Comment by Hansel03** [comment]
Hi, thanks for answering

1. yes it is injected into the component

`import { ToolbarService, LinkService, ImageService, HtmlEditorService, TableService } from '@syncfusion/ej2-angular-richtexteditor';`


`providers: [ToolbarService, LinkService, ImageService, HtmlEditorService, TableService]`



2.  My module

`import { RichTextEditorAllModule } from '@syncfusion/ej2-angular-richtexteditor';`

`imports: [
....
RichTextEditorAllModule
]
`

My html

`<ejs-richtexteditor formControlName="message" [toolbarSettings]='tools' [locale]='locale'>
            </ejs-richtexteditor>`

3. No error occurs at compile time, the project is built for production perfectly but at runtime the component  rich text editor does not appear and it only shows in console the error mentioned above.  The component rich text editor works perfectly in the development environment


4. The developing behavior is as follows

[Develop](https://vimeo.com/351318983)

in prod

[Prod](https://vimeo.com/351319345)

**Comment by NarayanasamyPanneerselvam** [comment]
Hi @Hansel03 ,

Thanks for sharing details.

We have checked your shared video. But, unfortunately we were unable to reproduce your reported issue on our end. We had tried to build the application using ‘**ng build --prod --aot**’ command and had run the application using **‘ng serve --prod --aot**’ command.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/RTE_AOT678250029 

Please share the below information,
•	Share your Angular CLI version.
•	If possible, to share your complete application to reproduce your issue and share the replication procedure.

The above-mentioned command is correct for running the application to reproducing your issue at our end?

Also, we are available to validate your issue through web meeting. Please let us know your availability to resolve your issue. We will schedule meeting once you are update further details through Syncfusion support system.

Regards,
Narayanasamy P.

**Comment by Hansel03** [comment]
I share the complete project, in the richtexteditor branch you can download it and perform the test with the following command 

`npm run serve-prod`

thank you

**Comment by NarayanasamyPanneerselvam** [comment]
Hi @Hansel03 ,

As per your comment. Can you please share runnable sample to replicate your issue?


Regards,
Narayanasamy P.

**Comment by Hansel03** [comment]
Hi @NarayanasamyPanneerselvam 

Yes, I have shared the repository, where you will find a branch "richtexteditor", that can be downloaded to perform the test and replicate the error.

![image](https://user-images.githubusercontent.com/8334348/62380270-e22cb700-b516-11e9-9895-d4ff2ea31ee4.png)


![image](https://user-images.githubusercontent.com/8334348/62380371-0f796500-b517-11e9-8b5b-c94f5c333809.png)

**Comment by pandiyarajm** [comment]
Hi @Hansel03,

Can you share the invite to me, we will check and update.

Regards,
Pandiyaraj M

**Comment by Hansel03** [comment]
Hi @pandiyarajm,

I have shared the project, the branch to prove the defect is  "richtexteditor"

thank you

**Comment by pandiyarajm** [comment]
Hi @Hansel03 ,

Can you share the login credentials of your application, we unable to navigate shoppers page without login.

Regards,
Pandiyaraj M

**Comment by Hansel03** [comment]
Hi @pandiyarajm 

in the README.md of the richtexteditor branch  are the login credentials of the application

username = hanselcapillo@hotmail.com pass = Asd123456

thank you

**Comment by pandiyarajm** [comment]
Hi @Hansel03 ,

I have validated reported issue with shared branch application, RTE rendered properly and console error not occur from our end.

Used following command for build & run the application:
` ng build --prod --aot` and  `ng serve --prod --aot`

As the previous update, you shared below command not available in your application
`npm run serve-prod`

Regards,
Pandiyaraj M

**Comment by Hansel03** [comment]
Hi @pandiyarajm 

which branch has been downloaded? Well, in the development branch it works.

I have uploaded the defect test to the richtexteditor branch

**Comment by pandiyarajm** [comment]
Hi @Hansel03 ,

I have downloaded development branch. Now this repo not accessible, can you please check and provide access

Regards,
Pandiyaraj M

**Comment by Hansel03** [comment]
Hi @pandiyarajm 

No, I have always said that the branch where the defect is is **richtexteditor**.

you must be on the branch **richtexteditor**


`git checkout richtexteditor`

`npm run serve-prod`

**Comment by pandiyarajm** [comment]
Hi @Hansel03 

Sorry for a delayed reply from our end.

We have validated reported issue using new angular project with RichTextEditor component is working fine from our end.

We are able to reproduce the reported issue in the shared repo with your application when **tsconfig.json** file **target** property configured as **es2015** alone. 

we are currently checking to find the root cause. Until we suggest you change **tsconfig.json** file **target** config as **es5** in your application and it will work properly.

Regards,
Pandiyaraj M

**Comment by Hansel03** [comment]
Hi @pandiyarajm 

Thank you, I have done the test and it works by changing the property to **es5**
