### ISSUE TITLE
ejs-dashboardlayout panel content

### ISSUE THREAD

**Issue by hnassr** [syncfusion/ej2-angular-ui-components#46]
Hello team,

Is there any way to add angular component as a panel content ?

for example like this:
```javascript
let panel: PanelModel[] = [{
    'id': this.count.toString(), 'sizeX': 1, 'sizeY': 1, 'row': 0, 'col': 0,
    content: CounterComponent
}];
this.dashboard.addPanel(panel[0]);
```
if not, is there another way ? I want to add component when user click on bottom

Best Regards

**Comment by sujithvj** [comment]
Hi,

Greetings from Syncfusion !!!

We have achieved your requirement to add an angular component as the panel content at our end in the below sample. Please check it.

**Sample Link:** https://stackblitz.com/edit/angular-ayu6wb?file=src%2Fapp%2Ftemplate-item.ts

Here, we have added the custom component to be rendered in the dynamic panel within the ng-template with a template reference along with a ng- container as shown below.

`
<ng-template #gridTemplate>
    <div style="height:100%; width: 100%;" class="templateContent">
        <grid-root></grid-root>
    </div>
</ng-template>

<ng-container #viewContainer></ng-container>`

In the script side on clicking the button, this template has been initialized to get render in the DOM and the rendered template appended is added as the content of the panel as shown in the below code.

`BtnClick() {
            // adding panel dynamically
            let panel: PanelModel[] = [{
                id: "layout_" + this.count.toString(),
                'sizeX': 4, 'sizeY': 2, 'row': 2, 'col': 0,
            }];
            this.Dashboard.addPanel(panel[0]);
            //rendes the (gridTemplate) temaplte in dom
            const templateValue = this.gridTemplate.createEmbeddedView(null);
            // inserts the template into the view container
            this.viewContainer.insert(templateValue);
            // Obtaining the content element of the panel
            let panel_Content = document.getElementById("layout_" + this.count.toString() + "_content");
            // appending the template to the panel content element.
            panel_Content.appendChild(templateValue.rootNodes[0]);
            this.count++;
}`

Please let us know if this sample meets your requirement or not and get back to if you need any further assistance.

Regards,
Sujith R

**Comment by TateTTW** [comment]
Really should be made easier

**Comment by Tjax33** [comment]
There needs to be a better way to do this. We should be able to easily use cdkportal to insert components into the panel.
