### ISSUE TITLE
Change the place of date-range picker

### ISSUE THREAD

**Issue by anoopyadav-kiwi** [syncfusion/ej2-angular-ui-components#50]
Hello Team,

I want to change the place of date-range picker when it's open. I also attached the link of the screenshot of the issue.

Link: https://www.screencast.com/t/6bip4XK3bQ

Thanks in Advance.

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

Greetings from Syncfusion support. 

We can position the popup of the DateRangePicker in the required place by setting the popup position for **X and Y as “top, left, right and bottom”** or any **value in number** like “**args.popup.position = {X:0, Y:0}**" as per your requirement in the **open** event. Please refer the below code example.

[**app.component.html**]

```html
<ejs-daterangepicker id="daterange" (open)="onOpen($event)"></ejs-daterangepicker>
```

[**app.component.ts**]

```ts
onOpen(args) {
    args.popup.position = { X: 768, Y: 0 };
}
```

Please find the sample from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-8tk3jb?file=main.ts 

Regards,
Berly B.C

**Comment by anoopyadav-kiwi** [comment]
Thanks for your quick response.

When I used your solution date picker always open from desired space, but when I open date picker in the small devices then it was not open at the correct position.

Can you please tell me one thing, how I can open date-range picker inside my container? Currently, it open outside the body tag.

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

**Query 1:**

When I used your solution date picker always open from the desired space, but when I open date picker in the small devices then it was not open at the correct position.

**Response:**

From the provided update, we suspect that you want to display the DateRangePicker popup after the label filter either or using the below work around solutions. 

**Solution 1:**

You can set the popup position **X as ”left” and Y as “bottom”  in the open event** to open the DateRangePicker popup from the input as mentioned in the below code example.

```ts
onOpen(args) {
    args.popup.position = { X: "left", Y: "bottom" };
  }
```

Please find the sample from the below link.

**Sample Link:** https://stackblitz.com/edit/angular-8tk3jb-rqzm8u?file=app.component.ts

**Solution 2:**

Else you can set the **offsetX position as per your requirement** to position the DateRangePicker popup after the input of the right side as mentioned in the below code example. Here, we have provided the offsetX value based on the desktop mode. You can customize it based on the view port. 

```ts
onOpen(args) {
       args.popup.offsetX=500;
  }
```

Please find the sample from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-8tk3jb-kdouxs?file=app.component.ts 

Else, you can customize the already provided workaround solution based on the viewport dimension to place the DateRangePicker popup in the desired place. 

**Query 2:**

Can you please tell me one thing, how I can open a date-range picker inside my container? Currently, it open outside the body tag.

**Answer:**

Currently, the DateRangePicker popup element placed outside of the wrapper element is the d**efault behavior in our popup related component**. Currently, there is no option to place the DateRangePicker popup in the desired place. We have considered this support as the feature at our end and this support will be included in any one of our upcoming releases. 

You can track the status of this feature from the below feedback link.

**Feedback Link:** https://www.syncfusion.com/feedback/8526/need-to-provide-appendto-support-for-daterangepicker-component 

Still facing issues or misunderstood your requirement, please revert us with issue reproducing sample or exact requirement that will help us to check and provide the exact solution at our end. 


Regards,
Berly B.C

**Comment by anoopyadav-kiwi** [comment]
Thanks for your reply.

Let me try this solution, and for now, I'm closing this issue.
