### ISSUE TITLE
Update ej2 components for angular 8.3.0 compatibility

### ISSUE THREAD

**Issue by samarmeena** [syncfusion/ej2-angular-ui-components#52]
ej2-filemanager is not working in production built on angular 8.3.0. thus in the production build, the default values are not passed which give lots of errors. 

The current version is only supportive to angular 7 only.

**Comment by BerlyChristopher** [comment]
Hi Samarmeena,

We have checked your reported query for rendering File Manager in angular 8. We were able to pass the default value of the file manager but facing some alignment issue while rendering File Manager in angular 8 and above version. Currently, we are validating the issue and we will update the details on 4th September 2019.

If it is not meet your requirement or if you are facing any other issue, then share any additional details or simple sample/video. It will helpful for us to validate your issue and provide the solution as soon as possible.

Regards,
Berly B.C
