### ISSUE TITLE
Draggable dialog with target inside scrollable area

### ISSUE THREAD

**Issue by mkvlpl** [syncfusion/ej2-angular-ui-components#53]
It seems that drag functionality for dialogs breaks when they're attached to certain target area that's placed inside a scrollable (and scrolled) parent.

Example:

https://stackblitz.com/edit/angular-f88pgc

![GitHub Logo](https://i.imgur.com/CMyFidS.gif)

**Comment by pandiyarajm93** [comment]
Hi @mkvlpl ,

Greetings from Syncfusion support.

This is a known issue from our end and we have logged this issue internally. Currently, we are working on this issue and the fix will be included in our upcoming 2019 Vol 3 beta release which is scheduled on mid of September.

Regards,
Pandiyaraj M

**Comment by mkvlpl** [comment]
Hello,

I can see that you released the 2019 vol 3 beta last Friday.

Going through [release notes](https://ej2.syncfusion.com/angular/documentation/release-notes/17.3.9/) and looking quickly at code changes I can't see any fix for this bug. Is it included? If not, when can we expect it to be?

**Comment by pandiyarajm93** [comment]
Hi @mkvlpl ,

Due to some technical complexity and ensure the fix in all possible case from our end, we not included in beta release and it will be included in our **Vol 3 Main release** which is expected on before October first week.

We appreciate your patience until then.

Regards,
Pandiyaraj M

**Comment by pandiyarajm93** [comment]
Hi @mkvlpl ,

Good day to you.

We have resolved the reported issue in weekly patch release version **17.3.16**.

**Sample**: https://stackblitz.com/edit/angular-f88pgc-hzp9yg?file=package.json

We suggest you upgrade to the latest package to resolve this issue.

Regards,
Pandiyaraj M

**Comment by rajendranr-5483** [comment]
HI @mkvlpl ,

We resolved your reported issue already.

We close this thread now due to long pending.
