### ISSUE TITLE
Grid column reordering with custom header template

### ISSUE THREAD

**Issue by akushnikov** [syncfusion/ej2-angular-ui-components#6]
#### What is the expected behavior?

Reordering should work with custom header template

#### What is the current behavior?

`a.headerTemplate.indexOf is not a function`

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-sh2e7k

#### Package versions:

```
"@syncfusion/ej2-angular-grids": "^16.3.34",
"@angular/animations": "^7.1.0",
"@angular/common": "^7.1.0",
"@angular/compiler": "^7.1.0",
"@angular/core": "^7.1.0",
"@angular/forms": "^7.1.0",
"@angular/http": "^7.1.0",
"@angular/platform-browser": "^7.1.0",
"@angular/platform-browser-dynamic": "^7.1.0",
"@angular/router": "^7.1.0",
```

**Comment by Madhust** [comment]
Hi @akushnikov,

Thanks for your patience. We have fixed the issue “**_Script error thrown when reorder header template column in Grid using Angular_**”. Please upgrade to the latest version **v16.4.44** to resolve this issue.

Regards,
Madhu Sudhanan P

**Comment by akushnikov** [comment]
Hi @thavasianand & @Madhust.

Issue has been resolved.
