### ISSUE TITLE
diagram node html

### ISSUE THREAD

**Issue by ManikantaJNSVV** [syncfusion/ej2-angular-ui-components#60]
angular directives like *ngIf , *ngFor and button click are not working when node content is html using angular diagram. How angular directives will work on node content html code..?? Can any one help me..??

**Comment by gshyam93** [comment]
Hi Manikanta,

Thanks for contacting Syncfusion products.

We have created a sample to achieve your requirement. We have defined a Html content with angular directives in app.component.html file and set that content in html node content property in created event. Please refer to a code example and sample below.


App.component.html                               <div   id='data'>                                                   <div   *ngFor="let id of ids">Id is {{id}}                                                                   <div   *ngIf="id%2 == 0">                                                                                   <div   [ngClass]="'one'">Even Number</div>                                                                   </div>                                                                   <div   *ngIf="id%2 == 1">                                                                                   <div   [ngClass]="'two'">Odd Number</div>                                                                   </div>                                                   </div>                                   </div>              App.component.ts         // Initializes the nodes   for the diagram.       public nodes:   NodeModel[] = [            {              id:   'Terminator', width: 100, height: 100, offsetX: 200, offsetY: 200, shape:   {   type: 'HTML',              //html content              content:   '<div   style="background:#6BA5D7;height:100%;width:100%;"><button   #first id="first" type="button" style="width:100px">   Button</button></div>' },            },                 {              id:   'conditionNode', width: 100, height: 100, offsetX: 200, offsetY: 400, shape:   {   type: 'HTML',              //html content              content: '' },            },                   ];           //created event     public created(): void   {       // set an html content   dynamically         (this.diagram.nodes[1].shape as any).content =   document.getElementById("data");         this.diagram.dataBind();           //click event for   button         document.getElementById("first").onclick = function() {         alert("first   button clicked")       }      }
--

Sample:  https://stackblitz.com/edit/angular-nxmvpt-ysep2z?file=app.component.ts

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
We have already provided a solution. So we will close this issue.
