### ISSUE TITLE
ej2-angular-schedule : Cannot read property 'reset' of null

### ISSUE THREAD

**Issue by Hasan-git** [syncfusion/ej2-angular-ui-components#63]
![image](https://user-images.githubusercontent.com/8820596/65532554-b02b4600-df04-11e9-85bb-2ad553c48585.png)

**Comment by vinithadevi** [comment]
Hi Hasan,

Syncfusion Greetings.

The reported problem with “TypeError: Cannot read property ‘rest’ of null ” has been fixed internally and the fix will be included in Volume 3, 2019 main release which is expected to be rolled out in the first week of October 2019. We appreciate your valuable patience until then. 

Regards,
M.Vinitha devi

**Comment by sellakumark** [comment]
Hi Hasan,

Fix included in Volume 3, 2019 release (v17.3.0.14) and upgrade your version to avail the fix. Please find the below release notes. 
https://ej2.syncfusion.com/angular/documentation/release-notes/17.3.14/#schedule
https://www.syncfusion.com/feedback/8669/typeerror-cannot-read-property-reset-of-null

Regards,
Sella

**Comment by rajendranr-5483** [comment]
HI @Hasan-git ,

We resolved your reported issue in Scheduler component.

We are closing this thread now due to long pending.
