### ISSUE TITLE
ej2-angular-base peer dependencies

### ISSUE THREAD

**Issue by nessche** [syncfusion/ej2-angular-ui-components#64]
ej2-angular-base@17.2.49 has a peer dependencies to angular core libraries 2.2.1 - 8.0.0, but now latest angular version is at 8.2.7, which means that newer angular projects generate warning about missing peer dependencies.

**Comment by gurunathancs1991** [comment]
Hi @nessche , 

Thanks for contacting Syncfusion. 

We have logged “Update peer dependency in angular” as an issue. We will fix this issue and provide the patch on volume 3, 2019 release which is scheduled to release by first week of October, 2019.

Regards,
Gurunathan

**Comment by Mydeen-SN** [comment]
Hi @nessche 

Thanks for the patience.

We have updated the peer dependency for EJ2 angular components and changes are reflected in the latest packages

https://www.npmjs.com/package/@syncfusion/ej2-angular-base/v/17.3.26

Regards,
Mydeen S N
