### ISSUE TITLE
ej2-angular-schedule : Cannot find the onCancel() event for cancel button in popup. 

### ISSUE THREAD

**Issue by VigneshMohanrajInvensis** [syncfusion/ej2-angular-ui-components#65]
We are using ej2-angular-schedule in our mini project. So, we need to do some operations when the user clicks the cancel button in the create schedule popup.

So kindly let us know how can we trigger a onCancel() event when the user clicks cancel button.

**Comment by sellakumark** [comment]
Hi Vignesh,

Syncfusion greetings.

We can bind the custom event to the close button using **created** event like below.
https://stackblitz.com/edit/angular-mm1kwg-s7ml8t?file=default.component.ts

public cancelClick(): void {
    let dialogObj: Dialog = (document.querySelector(
      ".e-schedule-dialog.e-popup-open"
    ) as EJ2Instance).ej2_instances[0] as Dialog;
    dialogObj.hide();
    alert("Cancel button clicked");
  }

  public onCreate(): void {
    (this.scheduleObj.eventWindow
      .dialogObject as any).btnObj[2].element.onclick = this.cancelClick;
  }

Regards,
Karthi

**Comment by sellakumark** [comment]
Hi Vignesh,

Syncfusion greetings.

We can bind the custom event to the close button using created event like below.
https://stackblitz.com/edit/angular-mm1kwg-s7ml8t?file=default.component.ts

public cancelClick(): void {
let dialogObj: Dialog = (document.querySelector(
".e-schedule-dialog.e-popup-open"
) as EJ2Instance).ej2_instances[0] as Dialog;
dialogObj.hide();
alert("Cancel button clicked");
}

public onCreate(): void {
(this.scheduleObj.eventWindow
.dialogObject as any).btnObj[2].element.onclick = this.cancelClick;
}

Regards,
Sella

**Comment by rajendranr-5483** [comment]
@VigneshMohanrajInvensis ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns about this requirement.
