### ISSUE TITLE
Dynamic theme support

### ISSUE THREAD

**Issue by fmavdb** [syncfusion/ej2-angular-ui-components#70]
Is it possible to dynamically change the syncfusion theme from for example dark to light? Just by changing the CSS class?

Right now we need to build multiple versions of our application to switch themes.

**Comment by gurunathancs1991** [comment]
Hi @fmavdb ,

Thanks for contacting Syncfusion. 

We don’t have to dynamically change the Syncfusion theme based on CSS class. However, we can achieve dynamically change Syncfusion theme via theme switcher, we created simple sample for dynamic theme change based on dropdown value.
In this sample, we make a ajax request and appending the styles in the web page dynamically using dropdown value.
https://www.syncfusion.com/downloads/support/directtrac/251515/ze/ej2-themeswitcher209314020

Please let us know if any concerns.

Regards,
Gurunathan

**Comment by fmavdb** [comment]
Hey Gurunathan,

We are unable to download the sample application due to access permissions.

With best regards,
Frank

**Comment by vairamuthuR** [comment]
Hi @fmavdb,

Please find the sample from the below attachment

[ej2-themeswitcher.zip](https://github.com/syncfusion/ej2-angular-ui-components/files/3753925/ej2-themeswitcher.zip)

Regards,
Vairamuthu R

**Comment by ajithr** [comment]
Hi @fmavdb,

We hope your requirement has been achieved with the provided sample. Please get back to us if you need any further assistance with this.

Regards,
Ajith R
