### ISSUE TITLE
date-range-picker: 'Today' text is not translated

### ISSUE THREAD

**Issue by fmavdb** [syncfusion/ej2-angular-ui-components#71]
Hello,

The text 'Today' in the date-range-picker component can not be translated. It's also not listed in the component documentation page:
https://ej2.syncfusion.com/documentation/daterangepicker/globalization/

With best regards,
Frank

**Comment by BerlyChristopher** [comment]
Hi Fmavdb,

Greetings from Syncfusion support.

While checking the reported query, we would like to inform you that DateRangePicker does not have a **Today** button in the popup and DatePicker having this label on its popup. So, we can change the today button text of the DatePicker as mentioned in the below code example. 

DateRangePicker popup:

![daternagepicke](https://user-images.githubusercontent.com/31254853/66741609-89bd5280-ee93-11e9-8e85-2761b9851f3d.png)

DatePicker popup:

![datepicker](https://user-images.githubusercontent.com/31254853/66741625-8fb33380-ee93-11e9-885f-154c10532b2b.png)

[app.component.ts]

```ts
//Load the L10n from ej2-base
import { L10n } from '@syncfusion/ej2-base'; 
export class AppComponent {
   ngOnInit() {
    //load the locale object to set the localized placeholder value
    L10n.load({
      'en-US': {
        'datepicker': {
          placeholder: 'Wählen Sie ein Datum aus',
          today: 'heute'
        }
      }
    });
  }
}
```

Please find the sample for DatePicker from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-1h1skw-lf6wp8?file=app.component.ts

Also, If you are facing any other issues in DateRangePicker, please let us know. We will happy to assist you. 

Regards,
Berly B.C

**Comment by fmavdb** [comment]
Yes, I'm sorry we've made a mistake in our translations and made the assumption date-range-picker also used 'Today'.
