### ISSUE TITLE
when having multiple grids on the page and tabbing through, and error occurs when the focus goes outside the window

### ISSUE THREAD

**Issue by gerhardboer** [syncfusion/ej2-angular-ui-components#73]
steps to reproduce:
create a page with 2 or more grids
tab through all the fields, never use the mouse
when the last selectable item on the page loses focus, an error occures in the console

![image](https://user-images.githubusercontent.com/8514342/67953345-3830f980-fbef-11e9-8430-e712e4703597.png)

*edit*
This happens when a grid has no data returned from the DataManager datasource

**Comment by VigneshNatarajan27** [comment]
Hi @gerhardboer,

Sorry for the delay in getting back to you. 

We have analyzed the reported issue by preparing a sample as per your suggestion using our latest version packages. We are unable to reproduce the reported issue at our end. 

Sample: https://stackblitz.com/edit/angular-k6ibyy?file=app.component.html 

So we request you to ensure the reported issue with the latest version packages and if you are still facing the issue. kindly get back to us with more details. 

Regards,
Vignesh Natarajan

**Comment by syncsiva** [comment]
This issue has not had any activity for a week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
