### ISSUE TITLE
How to programmatically open the calendar?

### ISSUE THREAD

**Issue by jstechaut** [syncfusion/ej2-angular-ui-components#83]

**Comment by sureshkumar1115** [comment]
Hi @jstechaut ,

We can open the calendar by using our inbuild public show method. Kindly refer to the below code example.
[component.html]

> `<div class="control-section">

    <div id="control_wrapper">
        <ejs-datepicker #date></ejs-datepicker>
    </div>
    <div>
        <button (click)="onClick()" id="btn">ClickToOpenCalendar</button>
    </div>
</div>
`
[component.ts]

> `import { DatePickerComponent } from '@syncfusion/ej2-angular-calendars'`

> `@ViewChild("date") public dateObject: DatePickerComponent;`

> `onClick() { this.dateObject.show(); }`

We have created a sample based on your requirements. please find the sample here: https://stackblitz.com/edit/angular-sywzgk?file=app.component.ts 

To know more about our show method. please refer the below documentation: https://ej2.syncfusion.com/angular/documentation/api/datepicker#show 

Regards,
Sureshkumar P
