### ISSUE TITLE
I am using @syncfusion/ej2-angular-gantt and getting below error when I make a build of angular app.

### ISSUE THREAD

**Issue by chetanvolansys** [syncfusion/ej2-angular-ui-components#86]
ERROR in ./node_modules/@syncfusion/ej2-richtexteditor/src/rich-text-editor/base/rich-text-editor.js 375:21-32
"export 'load' (imported as 'events') was not found in '../base/constant'
ERROR in ./node_modules/@syncfusion/ej2-richtexteditor/src/rich-text-editor/base/interface.js 1:0
Module parse failed: Unterminated comment (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> /**export var executeGroup = {
|     'bold': {
|         command: 'Style',

**Comment by Indrajith-Sync** [comment]
Hi @chetanvolansys,

We regret for the inconvenience caused,

We have resolved the issue with the RichTextEditor packages and the fix is now available with the release version 17.4.48. 

Can you please upgrade your package to this version to resolve the issue from your end ?

Regards,
Indrajith

**Comment by chetanvolansys** [comment]
Hi @Indrajith-Sync 

Thanks for your updates I have installed 17.3.9-beta version and resolved my issue.

Thank you.
