### ISSUE TITLE
@syncfusion/ej2-angular-richtexteditor with Angular 9 don't work

### ISSUE THREAD

**Issue by ingeJulianLasso** [syncfusion/ej2-angular-ui-components#88]
I updated Angular 8 to 9 from scratch today, but the @syncfusion/ej2-angular-richtexteditor library in its version 17.4.49 doesn't show any errors but also doesn't render the control to be used.

```
Angular CLI: 9.0.1
Node: 12.15.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.1
@angular-devkit/core         9.0.1
@angular-devkit/schematics   9.0.1
@schematics/angular          9.0.1
@schematics/update           0.900.1
rxjs                         6.5.3
```
Any ideas? Thanks

**Comment by NarayanasamyP** [comment]
Hi Julian,

Good day to you.

Currently, we don’t have support to render EJ2 RichTextEditor component in Angular9 environment. We are working on providing Angular9 environment support for Syncfusion’ s EJ2 components. This will be included in the upcoming patch release at 19th February 2020. We are appreciate your patience until then.


Regards,
Narayanasamy P.

**Comment by ingeJulianLasso** [comment]
hello @NarayanasamyP 

Thank you for your response, I look forward to the update, thank you very much.

**Comment by NarayanasamyP** [comment]
Hi Julian,

Thanks for your patience.

We have provided Angular9 compatibility support for EJ2 RTE component. Kindly upgrade Syncfusion packages to latest version (17.4.51), to get it work.

Release notes: https://ej2.syncfusion.com/angular/documentation/release-notes/index/#common

packages has been pushed to npmjs server: https://www.npmjs.com/~syncfusionorg

Regards,
Narayanasamy P.

**Comment by rajendranr-5483** [comment]
@ingeJulianLasso ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns about this requirement.
