### ISSUE TITLE
Production build with Grid has code that violates CSP

### ISSUE THREAD

**Issue by gerhardboer** [syncfusion/ej2-angular-ui-components#89]
We have a CSP active that checks for unsafe-eval, so no calls to eval() are allowed.

A production build using the grid has the following code:
`var __WEBPACK_AMD_DEFINE_RESULT__;
    __WEBPACK_AMD_DEFINE_RESULT__ = (function () {
      return "undefined" != typeof window ? window : new (eval("require('jsdom').JSDOM"))("").window
    }).call(exports, __webpack_require__, exports, module), void 0 === __WEBPACK_AMD_DEFINE_RESULT__ || (module.exports = __WEBPACK_AMD_DEFINE_RESULT__)
  }
`
Line that the CSP falls over: **eval("require('jsdom').JSDOM")**
I don't see why this code is inserterd, or that jsdom is needed in a production build.

**Comment by jvhariharan** [comment]
Hi @gerhardboer ,

We have checked your reported problem and tried to reproduce at our end but unfortunately were unable to reproduce it as the code you had mentioned was not added in our bundled file on running production build with Grid component. Please find below sample for your reference,

Sample: https://www.syncfusion.com/downloads/support/directtrac/266141/ze/GridApplication117427623 

Please share the following or more information that will helpful for us to validate and provide the proper solution as soon as possible.

•	Have you included any other components in your application other than grid. If so please let us know the components details
•	Share the Syncfusion component package and angular version details(share package.json file).
•	Share us the bundled file that contains the mentioned code.
•	If possible share us a simple sample to reproduce the problem or try replicating it in the above-provided sample.


Regards,
R.Dhivya

**Comment by gerhardboer** [comment]
I've traced the issue to another package. It occured when we added the syncfusion library, but it turned out another package was updated.

Sorry for the inconvenience
